/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlissServiceAreasFilter model module.
 * @module model/AlissServiceAreasFilter
 * @version 1.0.0
 */
class AlissServiceAreasFilter {
    /**
     * Constructs a new <code>AlissServiceAreasFilter</code>.
     * Filter applied to the service_areas dataset. The condition property is required for every filter except the final filter.
     * @alias module:model/AlissServiceAreasFilter
     * @param field {module:model/AlissServiceAreasFilter.FieldEnum} 
     * @param value {String} 
     * @param operator {module:model/AlissServiceAreasFilter.OperatorEnum} 
     */
    constructor(field, value, operator) { 
        
        AlissServiceAreasFilter.initialize(this, field, value, operator);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, field, value, operator) { 
        obj['field'] = field;
        obj['value'] = value;
        obj['operator'] = operator;
    }

    /**
     * Constructs a <code>AlissServiceAreasFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlissServiceAreasFilter} obj Optional instance to populate.
     * @return {module:model/AlissServiceAreasFilter} The populated <code>AlissServiceAreasFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlissServiceAreasFilter();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('condition')) {
                obj['condition'] = ApiClient.convertToType(data['condition'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AlissServiceAreasFilter</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AlissServiceAreasFilter</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AlissServiceAreasFilter.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['field'] && !(typeof data['field'] === 'string' || data['field'] instanceof String)) {
            throw new Error("Expected the field `field` to be a primitive type in the JSON string but got " + data['field']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['operator'] && !(typeof data['operator'] === 'string' || data['operator'] instanceof String)) {
            throw new Error("Expected the field `operator` to be a primitive type in the JSON string but got " + data['operator']);
        }
        // ensure the json data is a string
        if (data['condition'] && !(typeof data['condition'] === 'string' || data['condition'] instanceof String)) {
            throw new Error("Expected the field `condition` to be a primitive type in the JSON string but got " + data['condition']);
        }

        return true;
    }


}

AlissServiceAreasFilter.RequiredProperties = ["field", "value", "operator"];

/**
 * @member {module:model/AlissServiceAreasFilter.FieldEnum} field
 */
AlissServiceAreasFilter.prototype['field'] = undefined;

/**
 * @member {String} value
 */
AlissServiceAreasFilter.prototype['value'] = undefined;

/**
 * @member {module:model/AlissServiceAreasFilter.OperatorEnum} operator
 */
AlissServiceAreasFilter.prototype['operator'] = undefined;

/**
 * @member {module:model/AlissServiceAreasFilter.ConditionEnum} condition
 */
AlissServiceAreasFilter.prototype['condition'] = undefined;





/**
 * Allowed values for the <code>field</code> property.
 * @enum {String}
 * @readonly
 */
AlissServiceAreasFilter['FieldEnum'] = {

    /**
     * value: "id"
     * @const
     */
    "id": "id",

    /**
     * value: "name"
     * @const
     */
    "name": "name",

    /**
     * value: "type"
     * @const
     */
    "type": "type",

    /**
     * value: "code"
     * @const
     */
    "code": "code",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};


/**
 * Allowed values for the <code>operator</code> property.
 * @enum {String}
 * @readonly
 */
AlissServiceAreasFilter['OperatorEnum'] = {

    /**
     * value: "="
     * @const
     */
    "EQUAL": "=",

    /**
     * value: "LIKE"
     * @const
     */
    "LIKE": "LIKE",

    /**
     * value: "IN"
     * @const
     */
    "IN": "IN",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};


/**
 * Allowed values for the <code>condition</code> property.
 * @enum {String}
 * @readonly
 */
AlissServiceAreasFilter['ConditionEnum'] = {

    /**
     * value: "AND"
     * @const
     */
    "AND": "AND",

    /**
     * value: "OR"
     * @const
     */
    "OR": "OR",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default AlissServiceAreasFilter;

