/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlissCommunityGroup model module.
 * @module model/AlissCommunityGroup
 * @version 1.0.0
 */
class AlissCommunityGroup {
    /**
     * Constructs a new <code>AlissCommunityGroup</code>.
     * @alias module:model/AlissCommunityGroup
     */
    constructor() { 
        
        AlissCommunityGroup.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AlissCommunityGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlissCommunityGroup} obj Optional instance to populate.
     * @return {module:model/AlissCommunityGroup} The populated <code>AlissCommunityGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlissCommunityGroup();

            if (data.hasOwnProperty('displayorder')) {
                obj['displayorder'] = ApiClient.convertToType(data['displayorder'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('isrange')) {
                obj['isrange'] = ApiClient.convertToType(data['isrange'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'String');
            }
            if (data.hasOwnProperty('sub_communitygroups')) {
                obj['sub_communitygroups'] = ApiClient.convertToType(data['sub_communitygroups'], [AlissCommunityGroup]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AlissCommunityGroup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AlissCommunityGroup</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['parent_id'] && !(typeof data['parent_id'] === 'string' || data['parent_id'] instanceof String)) {
            throw new Error("Expected the field `parent_id` to be a primitive type in the JSON string but got " + data['parent_id']);
        }
        if (data['sub_communitygroups']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sub_communitygroups'])) {
                throw new Error("Expected the field `sub_communitygroups` to be an array in the JSON data but got " + data['sub_communitygroups']);
            }
            // validate the optional field `sub_communitygroups` (array)
            for (const item of data['sub_communitygroups']) {
                AlissCommunityGroup.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} displayorder
 */
AlissCommunityGroup.prototype['displayorder'] = undefined;

/**
 * @member {String} id
 */
AlissCommunityGroup.prototype['id'] = undefined;

/**
 * @member {Boolean} isrange
 */
AlissCommunityGroup.prototype['isrange'] = undefined;

/**
 * @member {String} name
 */
AlissCommunityGroup.prototype['name'] = undefined;

/**
 * @member {String} slug
 */
AlissCommunityGroup.prototype['slug'] = undefined;

/**
 * @member {Number} count
 */
AlissCommunityGroup.prototype['count'] = undefined;

/**
 * @member {String} parent_id
 */
AlissCommunityGroup.prototype['parent_id'] = undefined;

/**
 * @member {Array.<module:model/AlissCommunityGroup>} sub_communitygroups
 */
AlissCommunityGroup.prototype['sub_communitygroups'] = undefined;






export default AlissCommunityGroup;

