/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConditionAbout from './ConditionAbout';
import ConditionBreadcrumb from './ConditionBreadcrumb';
import ConditionContentNode from './ConditionContentNode';
import ConditionErrorResponse from './ConditionErrorResponse';
import ConditionHealthTopicContent from './ConditionHealthTopicContent';
import ConditionKeywords from './ConditionKeywords';
import ConditionOrganisation from './ConditionOrganisation';
import ConditionPage from './ConditionPage';
import ConditionRelatedLink from './ConditionRelatedLink';

/**
 * The ConditionResponse model module.
 * @module model/ConditionResponse
 * @version 1.0.0
 */
class ConditionResponse {
    /**
     * Constructs a new <code>ConditionResponse</code>.
     * A Conditions page, an array of matching pages, or an application-level error returned by the service.
     * @alias module:model/ConditionResponse
     * @param {(module:model/ConditionErrorResponse|module:model/ConditionPage|module:model/[ConditionPage])} instance The actual instance to initialize ConditionResponse.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof ConditionPage) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ConditionPage.validateJSON(instance); // throw an exception if no match
                // create ConditionPage from JS object
                this.actualInstance = ConditionPage.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ConditionPage
            errorMessages.push("Failed to construct ConditionPage: " + err)
        }

        try {
            if (instance instanceof [ConditionPage]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [ConditionPage].validateJSON(instance); // throw an exception if no match
                // create [ConditionPage] from JS object
                this.actualInstance = [ConditionPage].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [ConditionPage]
            errorMessages.push("Failed to construct [ConditionPage]: " + err)
        }

        try {
            if (instance instanceof ConditionErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ConditionErrorResponse.validateJSON(instance); // throw an exception if no match
                // create ConditionErrorResponse from JS object
                this.actualInstance = ConditionErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ConditionErrorResponse
            errorMessages.push("Failed to construct ConditionErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `ConditionResponse` with oneOf schemas ConditionErrorResponse, ConditionPage, [ConditionPage]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `ConditionResponse` with oneOf schemas ConditionErrorResponse, ConditionPage, [ConditionPage]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>ConditionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConditionResponse} obj Optional instance to populate.
     * @return {module:model/ConditionResponse} The populated <code>ConditionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        return new ConditionResponse(data);
    }

    /**
     * Gets the actual instance, which can be <code>ConditionErrorResponse</code>, <code>ConditionPage</code>, <code>[ConditionPage]</code>.
     * @return {(module:model/ConditionErrorResponse|module:model/ConditionPage|module:model/[ConditionPage])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>ConditionErrorResponse</code>, <code>ConditionPage</code>, <code>[ConditionPage]</code>.
     * @param {(module:model/ConditionErrorResponse|module:model/ConditionPage|module:model/[ConditionPage])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = ConditionResponse.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of ConditionResponse from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/ConditionResponse} An instance of ConditionResponse.
     */
    static fromJSON = function(json_string){
        return ConditionResponse.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} @context
 */
ConditionResponse.prototype['@context'] = undefined;

/**
 * @member {module:model/ConditionResponse.TypeEnum} @type
 */
ConditionResponse.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
ConditionResponse.prototype['name'] = undefined;

/**
 * @member {module:model/ConditionOrganisation} copyrightHolder
 */
ConditionResponse.prototype['copyrightHolder'] = undefined;

/**
 * @member {String} license
 */
ConditionResponse.prototype['license'] = undefined;

/**
 * @member {module:model/ConditionOrganisation} author
 */
ConditionResponse.prototype['author'] = undefined;

/**
 * @member {module:model/ConditionAbout} about
 */
ConditionResponse.prototype['about'] = undefined;

/**
 * @member {String} description
 */
ConditionResponse.prototype['description'] = undefined;

/**
 * MRD URL by default or the original NHS URL when nhs_links is enabled.
 * @member {String} url
 */
ConditionResponse.prototype['url'] = undefined;

/**
 * @member {Array.<String>} genre
 */
ConditionResponse.prototype['genre'] = undefined;

/**
 * @member {module:model/ConditionKeywords} keywords
 */
ConditionResponse.prototype['keywords'] = undefined;

/**
 * @member {Date} dateModified
 */
ConditionResponse.prototype['dateModified'] = undefined;

/**
 * The last review date followed by the next review-due date when supplied.
 * @member {Array.<Date>} lastReviewed
 */
ConditionResponse.prototype['lastReviewed'] = undefined;

/**
 * @member {module:model/ConditionBreadcrumb} breadcrumb
 */
ConditionResponse.prototype['breadcrumb'] = undefined;

/**
 * @member {Array.<module:model/ConditionHealthTopicContent>} hasPart
 */
ConditionResponse.prototype['hasPart'] = undefined;

/**
 * @member {Array.<module:model/ConditionRelatedLink>} relatedLink
 */
ConditionResponse.prototype['relatedLink'] = undefined;

/**
 * @member {Array.<String>} contentSubTypes
 */
ConditionResponse.prototype['contentSubTypes'] = undefined;

/**
 * @member {String} headline
 */
ConditionResponse.prototype['headline'] = undefined;

/**
 * @member {Array.<module:model/ConditionContentNode>} mainEntityOfPage
 */
ConditionResponse.prototype['mainEntityOfPage'] = undefined;

/**
 * @member {String} webpage
 */
ConditionResponse.prototype['webpage'] = undefined;

/**
 * @member {Number} id
 */
ConditionResponse.prototype['id'] = undefined;

/**
 * @member {String} route_mapping
 */
ConditionResponse.prototype['route_mapping'] = undefined;

/**
 * @member {module:model/ConditionResponse.SuccessEnum} success
 */
ConditionResponse.prototype['success'] = undefined;

/**
 * @member {String} message
 */
ConditionResponse.prototype['message'] = undefined;


ConditionResponse.OneOf = ["ConditionErrorResponse", "ConditionPage", "[ConditionPage]"];

export default ConditionResponse;

