/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConditionVideoObjectIdentifier from './ConditionVideoObjectIdentifier';

/**
 * The ConditionVideoObject model module.
 * @module model/ConditionVideoObject
 * @version 1.0.0
 */
class ConditionVideoObject {
    /**
     * Constructs a new <code>ConditionVideoObject</code>.
     * @alias module:model/ConditionVideoObject
     */
    constructor() { 
        
        ConditionVideoObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConditionVideoObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConditionVideoObject} obj Optional instance to populate.
     * @return {module:model/ConditionVideoObject} The populated <code>ConditionVideoObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConditionVideoObject();

            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('embedUrl')) {
                obj['embedUrl'] = ApiClient.convertToType(data['embedUrl'], 'String');
            }
            if (data.hasOwnProperty('contentUrl')) {
                obj['contentUrl'] = ApiClient.convertToType(data['contentUrl'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ConditionVideoObjectIdentifier.constructFromObject(data['identifier']);
            }
            if (data.hasOwnProperty('alternateName')) {
                obj['alternateName'] = ApiClient.convertToType(data['alternateName'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('uploadDate')) {
                obj['uploadDate'] = ApiClient.convertToType(data['uploadDate'], 'Date');
            }
            if (data.hasOwnProperty('lastReviewed')) {
                obj['lastReviewed'] = ApiClient.convertToType(data['lastReviewed'], ['String']);
            }
            if (data.hasOwnProperty('thumbnailUrl')) {
                obj['thumbnailUrl'] = ApiClient.convertToType(data['thumbnailUrl'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConditionVideoObject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConditionVideoObject</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['embedUrl'] && !(typeof data['embedUrl'] === 'string' || data['embedUrl'] instanceof String)) {
            throw new Error("Expected the field `embedUrl` to be a primitive type in the JSON string but got " + data['embedUrl']);
        }
        // ensure the json data is a string
        if (data['contentUrl'] && !(typeof data['contentUrl'] === 'string' || data['contentUrl'] instanceof String)) {
            throw new Error("Expected the field `contentUrl` to be a primitive type in the JSON string but got " + data['contentUrl']);
        }
        // ensure the json data is a string
        if (data['duration'] && !(typeof data['duration'] === 'string' || data['duration'] instanceof String)) {
            throw new Error("Expected the field `duration` to be a primitive type in the JSON string but got " + data['duration']);
        }
        // validate the optional field `identifier`
        if (data['identifier']) { // data not null
          ConditionVideoObjectIdentifier.validateJSON(data['identifier']);
        }
        // ensure the json data is a string
        if (data['alternateName'] && !(typeof data['alternateName'] === 'string' || data['alternateName'] instanceof String)) {
            throw new Error("Expected the field `alternateName` to be a primitive type in the JSON string but got " + data['alternateName']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lastReviewed'])) {
            throw new Error("Expected the field `lastReviewed` to be an array in the JSON data but got " + data['lastReviewed']);
        }
        // ensure the json data is a string
        if (data['thumbnailUrl'] && !(typeof data['thumbnailUrl'] === 'string' || data['thumbnailUrl'] instanceof String)) {
            throw new Error("Expected the field `thumbnailUrl` to be a primitive type in the JSON string but got " + data['thumbnailUrl']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }

        return true;
    }


}



/**
 * @member {String} @type
 */
ConditionVideoObject.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
ConditionVideoObject.prototype['name'] = undefined;

/**
 * @member {String} embedUrl
 */
ConditionVideoObject.prototype['embedUrl'] = undefined;

/**
 * @member {String} contentUrl
 */
ConditionVideoObject.prototype['contentUrl'] = undefined;

/**
 * @member {String} duration
 */
ConditionVideoObject.prototype['duration'] = undefined;

/**
 * @member {Number} position
 */
ConditionVideoObject.prototype['position'] = undefined;

/**
 * @member {module:model/ConditionVideoObjectIdentifier} identifier
 */
ConditionVideoObject.prototype['identifier'] = undefined;

/**
 * @member {String} alternateName
 */
ConditionVideoObject.prototype['alternateName'] = undefined;

/**
 * @member {String} description
 */
ConditionVideoObject.prototype['description'] = undefined;

/**
 * @member {Date} uploadDate
 */
ConditionVideoObject.prototype['uploadDate'] = undefined;

/**
 * @member {Array.<String>} lastReviewed
 */
ConditionVideoObject.prototype['lastReviewed'] = undefined;

/**
 * @member {String} thumbnailUrl
 */
ConditionVideoObject.prototype['thumbnailUrl'] = undefined;

/**
 * HTML video markup when no_html is false, or processed plain text when no_html is enabled.
 * @member {String} text
 */
ConditionVideoObject.prototype['text'] = undefined;






export default ConditionVideoObject;

