/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConditionAbout from './ConditionAbout';
import ConditionBreadcrumb from './ConditionBreadcrumb';
import ConditionContentNode from './ConditionContentNode';
import ConditionHealthTopicContent from './ConditionHealthTopicContent';
import ConditionKeywords from './ConditionKeywords';
import ConditionOrganisation from './ConditionOrganisation';
import ConditionRelatedLink from './ConditionRelatedLink';

/**
 * The ConditionPage model module.
 * @module model/ConditionPage
 * @version 1.0.0
 */
class ConditionPage {
    /**
     * Constructs a new <code>ConditionPage</code>.
     * An NHS Conditions page stored and returned by MRD. The structure varies between source records and may contain nested health-topic content, webpage elements and videos.
     * @alias module:model/ConditionPage
     * @param context {String} 
     * @param type {module:model/ConditionPage.TypeEnum} 
     * @param name {String} 
     * @param description {String} 
     * @param url {String} MRD URL by default or the original NHS URL when nhs_links is enabled.
     * @param id {Number} 
     * @param routeMapping {String} 
     */
    constructor(context, type, name, description, url, id, routeMapping) { 
        
        ConditionPage.initialize(this, context, type, name, description, url, id, routeMapping);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, context, type, name, description, url, id, routeMapping) { 
        obj['@context'] = context;
        obj['@type'] = type;
        obj['name'] = name;
        obj['description'] = description;
        obj['url'] = url;
        obj['id'] = id;
        obj['route_mapping'] = routeMapping;
    }

    /**
     * Constructs a <code>ConditionPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConditionPage} obj Optional instance to populate.
     * @return {module:model/ConditionPage} The populated <code>ConditionPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConditionPage();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('copyrightHolder')) {
                obj['copyrightHolder'] = ConditionOrganisation.constructFromObject(data['copyrightHolder']);
            }
            if (data.hasOwnProperty('license')) {
                obj['license'] = ApiClient.convertToType(data['license'], 'String');
            }
            if (data.hasOwnProperty('author')) {
                obj['author'] = ConditionOrganisation.constructFromObject(data['author']);
            }
            if (data.hasOwnProperty('about')) {
                obj['about'] = ConditionAbout.constructFromObject(data['about']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], ['String']);
            }
            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = ConditionKeywords.constructFromObject(data['keywords']);
            }
            if (data.hasOwnProperty('dateModified')) {
                obj['dateModified'] = ApiClient.convertToType(data['dateModified'], 'Date');
            }
            if (data.hasOwnProperty('lastReviewed')) {
                obj['lastReviewed'] = ApiClient.convertToType(data['lastReviewed'], ['Date']);
            }
            if (data.hasOwnProperty('breadcrumb')) {
                obj['breadcrumb'] = ConditionBreadcrumb.constructFromObject(data['breadcrumb']);
            }
            if (data.hasOwnProperty('hasPart')) {
                obj['hasPart'] = ApiClient.convertToType(data['hasPart'], [ConditionHealthTopicContent]);
            }
            if (data.hasOwnProperty('relatedLink')) {
                obj['relatedLink'] = ApiClient.convertToType(data['relatedLink'], [ConditionRelatedLink]);
            }
            if (data.hasOwnProperty('contentSubTypes')) {
                obj['contentSubTypes'] = ApiClient.convertToType(data['contentSubTypes'], ['String']);
            }
            if (data.hasOwnProperty('headline')) {
                obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
            }
            if (data.hasOwnProperty('mainEntityOfPage')) {
                obj['mainEntityOfPage'] = ApiClient.convertToType(data['mainEntityOfPage'], [ConditionContentNode]);
            }
            if (data.hasOwnProperty('webpage')) {
                obj['webpage'] = ApiClient.convertToType(data['webpage'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('route_mapping')) {
                obj['route_mapping'] = ApiClient.convertToType(data['route_mapping'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConditionPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConditionPage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ConditionPage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['@context'] && !(typeof data['@context'] === 'string' || data['@context'] instanceof String)) {
            throw new Error("Expected the field `@context` to be a primitive type in the JSON string but got " + data['@context']);
        }
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `copyrightHolder`
        if (data['copyrightHolder']) { // data not null
          ConditionOrganisation.validateJSON(data['copyrightHolder']);
        }
        // ensure the json data is a string
        if (data['license'] && !(typeof data['license'] === 'string' || data['license'] instanceof String)) {
            throw new Error("Expected the field `license` to be a primitive type in the JSON string but got " + data['license']);
        }
        // validate the optional field `author`
        if (data['author']) { // data not null
          ConditionOrganisation.validateJSON(data['author']);
        }
        // validate the optional field `about`
        if (data['about']) { // data not null
          ConditionAbout.validateJSON(data['about']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['genre'])) {
            throw new Error("Expected the field `genre` to be an array in the JSON data but got " + data['genre']);
        }
        // validate the optional field `keywords`
        if (data['keywords']) { // data not null
          ConditionKeywords.validateJSON(data['keywords']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lastReviewed'])) {
            throw new Error("Expected the field `lastReviewed` to be an array in the JSON data but got " + data['lastReviewed']);
        }
        // validate the optional field `breadcrumb`
        if (data['breadcrumb']) { // data not null
          ConditionBreadcrumb.validateJSON(data['breadcrumb']);
        }
        if (data['hasPart']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['hasPart'])) {
                throw new Error("Expected the field `hasPart` to be an array in the JSON data but got " + data['hasPart']);
            }
            // validate the optional field `hasPart` (array)
            for (const item of data['hasPart']) {
                ConditionHealthTopicContent.validateJSON(item);
            };
        }
        if (data['relatedLink']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['relatedLink'])) {
                throw new Error("Expected the field `relatedLink` to be an array in the JSON data but got " + data['relatedLink']);
            }
            // validate the optional field `relatedLink` (array)
            for (const item of data['relatedLink']) {
                ConditionRelatedLink.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['contentSubTypes'])) {
            throw new Error("Expected the field `contentSubTypes` to be an array in the JSON data but got " + data['contentSubTypes']);
        }
        // ensure the json data is a string
        if (data['headline'] && !(typeof data['headline'] === 'string' || data['headline'] instanceof String)) {
            throw new Error("Expected the field `headline` to be a primitive type in the JSON string but got " + data['headline']);
        }
        if (data['mainEntityOfPage']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['mainEntityOfPage'])) {
                throw new Error("Expected the field `mainEntityOfPage` to be an array in the JSON data but got " + data['mainEntityOfPage']);
            }
            // validate the optional field `mainEntityOfPage` (array)
            for (const item of data['mainEntityOfPage']) {
                ConditionContentNode.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['webpage'] && !(typeof data['webpage'] === 'string' || data['webpage'] instanceof String)) {
            throw new Error("Expected the field `webpage` to be a primitive type in the JSON string but got " + data['webpage']);
        }
        // ensure the json data is a string
        if (data['route_mapping'] && !(typeof data['route_mapping'] === 'string' || data['route_mapping'] instanceof String)) {
            throw new Error("Expected the field `route_mapping` to be a primitive type in the JSON string but got " + data['route_mapping']);
        }

        return true;
    }


}

ConditionPage.RequiredProperties = ["@context", "@type", "name", "description", "url", "id", "route_mapping"];

/**
 * @member {String} @context
 */
ConditionPage.prototype['@context'] = undefined;

/**
 * @member {module:model/ConditionPage.TypeEnum} @type
 */
ConditionPage.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
ConditionPage.prototype['name'] = undefined;

/**
 * @member {module:model/ConditionOrganisation} copyrightHolder
 */
ConditionPage.prototype['copyrightHolder'] = undefined;

/**
 * @member {String} license
 */
ConditionPage.prototype['license'] = undefined;

/**
 * @member {module:model/ConditionOrganisation} author
 */
ConditionPage.prototype['author'] = undefined;

/**
 * @member {module:model/ConditionAbout} about
 */
ConditionPage.prototype['about'] = undefined;

/**
 * @member {String} description
 */
ConditionPage.prototype['description'] = undefined;

/**
 * MRD URL by default or the original NHS URL when nhs_links is enabled.
 * @member {String} url
 */
ConditionPage.prototype['url'] = undefined;

/**
 * @member {Array.<String>} genre
 */
ConditionPage.prototype['genre'] = undefined;

/**
 * @member {module:model/ConditionKeywords} keywords
 */
ConditionPage.prototype['keywords'] = undefined;

/**
 * @member {Date} dateModified
 */
ConditionPage.prototype['dateModified'] = undefined;

/**
 * The last review date followed by the next review-due date when supplied.
 * @member {Array.<Date>} lastReviewed
 */
ConditionPage.prototype['lastReviewed'] = undefined;

/**
 * @member {module:model/ConditionBreadcrumb} breadcrumb
 */
ConditionPage.prototype['breadcrumb'] = undefined;

/**
 * @member {Array.<module:model/ConditionHealthTopicContent>} hasPart
 */
ConditionPage.prototype['hasPart'] = undefined;

/**
 * @member {Array.<module:model/ConditionRelatedLink>} relatedLink
 */
ConditionPage.prototype['relatedLink'] = undefined;

/**
 * @member {Array.<String>} contentSubTypes
 */
ConditionPage.prototype['contentSubTypes'] = undefined;

/**
 * @member {String} headline
 */
ConditionPage.prototype['headline'] = undefined;

/**
 * @member {Array.<module:model/ConditionContentNode>} mainEntityOfPage
 */
ConditionPage.prototype['mainEntityOfPage'] = undefined;

/**
 * @member {String} webpage
 */
ConditionPage.prototype['webpage'] = undefined;

/**
 * @member {Number} id
 */
ConditionPage.prototype['id'] = undefined;

/**
 * @member {String} route_mapping
 */
ConditionPage.prototype['route_mapping'] = undefined;





/**
 * Allowed values for the <code>@type</code> property.
 * @enum {String}
 * @readonly
 */
ConditionPage['TypeEnum'] = {

    /**
     * value: "MedicalWebPage"
     * @const
     */
    "MedicalWebPage": "MedicalWebPage",

    /**
     * value: "WebPage"
     * @const
     */
    "WebPage": "WebPage",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default ConditionPage;

