/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CountryPostalCode model module.
 * @module model/CountryPostalCode
 * @version 1.0.0
 */
class CountryPostalCode {
    /**
     * Constructs a new <code>CountryPostalCode</code>.
     * @alias module:model/CountryPostalCode
     * @param format {String} 
     * @param regex {String} 
     */
    constructor(format, regex) { 
        
        CountryPostalCode.initialize(this, format, regex);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, format, regex) { 
        obj['format'] = format;
        obj['regex'] = regex;
    }

    /**
     * Constructs a <code>CountryPostalCode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CountryPostalCode} obj Optional instance to populate.
     * @return {module:model/CountryPostalCode} The populated <code>CountryPostalCode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountryPostalCode();

            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('regex')) {
                obj['regex'] = ApiClient.convertToType(data['regex'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CountryPostalCode</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CountryPostalCode</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CountryPostalCode.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['format'] && !(typeof data['format'] === 'string' || data['format'] instanceof String)) {
            throw new Error("Expected the field `format` to be a primitive type in the JSON string but got " + data['format']);
        }
        // ensure the json data is a string
        if (data['regex'] && !(typeof data['regex'] === 'string' || data['regex'] instanceof String)) {
            throw new Error("Expected the field `regex` to be a primitive type in the JSON string but got " + data['regex']);
        }

        return true;
    }


}

CountryPostalCode.RequiredProperties = ["format", "regex"];

/**
 * @member {String} format
 */
CountryPostalCode.prototype['format'] = undefined;

/**
 * @member {String} regex
 */
CountryPostalCode.prototype['regex'] = undefined;






export default CountryPostalCode;

