/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CountryIdd model module.
 * @module model/CountryIdd
 * @version 1.0.0
 */
class CountryIdd {
    /**
     * Constructs a new <code>CountryIdd</code>.
     * International dialling information. If no dialling suffixes exist, the API returns an empty object.
     * @alias module:model/CountryIdd
     */
    constructor() { 
        
        CountryIdd.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CountryIdd</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CountryIdd} obj Optional instance to populate.
     * @return {module:model/CountryIdd} The populated <code>CountryIdd</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountryIdd();

            if (data.hasOwnProperty('root')) {
                obj['root'] = ApiClient.convertToType(data['root'], 'String');
            }
            if (data.hasOwnProperty('suffixes')) {
                obj['suffixes'] = ApiClient.convertToType(data['suffixes'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CountryIdd</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CountryIdd</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['root'] && !(typeof data['root'] === 'string' || data['root'] instanceof String)) {
            throw new Error("Expected the field `root` to be a primitive type in the JSON string but got " + data['root']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['suffixes'])) {
            throw new Error("Expected the field `suffixes` to be an array in the JSON data but got " + data['suffixes']);
        }

        return true;
    }


}



/**
 * @member {String} root
 */
CountryIdd.prototype['root'] = undefined;

/**
 * @member {Array.<String>} suffixes
 */
CountryIdd.prototype['suffixes'] = undefined;






export default CountryIdd;

