/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CountriesErrorDetails from './CountriesErrorDetails';

/**
 * The CountriesErrorResponse model module.
 * @module model/CountriesErrorResponse
 * @version 1.0.0
 */
class CountriesErrorResponse {
    /**
     * Constructs a new <code>CountriesErrorResponse</code>.
     * @alias module:model/CountriesErrorResponse
     * @param error {module:model/CountriesErrorDetails} 
     */
    constructor(error) { 
        
        CountriesErrorResponse.initialize(this, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error) { 
        obj['error'] = error;
    }

    /**
     * Constructs a <code>CountriesErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CountriesErrorResponse} obj Optional instance to populate.
     * @return {module:model/CountriesErrorResponse} The populated <code>CountriesErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountriesErrorResponse();

            if (data.hasOwnProperty('error')) {
                obj['error'] = CountriesErrorDetails.constructFromObject(data['error']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CountriesErrorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CountriesErrorResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CountriesErrorResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `error`
        if (data['error']) { // data not null
          CountriesErrorDetails.validateJSON(data['error']);
        }

        return true;
    }


}

CountriesErrorResponse.RequiredProperties = ["error"];

/**
 * @member {module:model/CountriesErrorDetails} error
 */
CountriesErrorResponse.prototype['error'] = undefined;






export default CountriesErrorResponse;

