/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LivewellAboutAlternateName from './LivewellAboutAlternateName';
import MentalHealthAbout from './MentalHealthAbout';
import MentalHealthAuthor from './MentalHealthAuthor';
import MentalHealthBreadcrumb from './MentalHealthBreadcrumb';
import MentalHealthContentElementMainEntityOfPageInner from './MentalHealthContentElementMainEntityOfPageInner';
import MentalHealthCopyrightHolder from './MentalHealthCopyrightHolder';
import MentalHealthData from './MentalHealthData';
import MentalHealthExpanderGroup from './MentalHealthExpanderGroup';
import MentalHealthHealthTopicContent from './MentalHealthHealthTopicContent';
import MentalHealthNotFoundResponse from './MentalHealthNotFoundResponse';
import MentalHealthRelatedLink from './MentalHealthRelatedLink';

/**
 * The GetMentalHealthLevelOne200Response model module.
 * @module model/GetMentalHealthLevelOne200Response
 * @version 1.0.0
 */
class GetMentalHealthLevelOne200Response {
    /**
     * Constructs a new <code>GetMentalHealthLevelOne200Response</code>.
     * @alias module:model/GetMentalHealthLevelOne200Response
     * @param {(module:model/MentalHealthData|module:model/MentalHealthNotFoundResponse)} instance The actual instance to initialize GetMentalHealthLevelOne200Response.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MentalHealthData) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MentalHealthData.validateJSON(instance); // throw an exception if no match
                // create MentalHealthData from JS object
                this.actualInstance = MentalHealthData.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MentalHealthData
            errorMessages.push("Failed to construct MentalHealthData: " + err)
        }

        try {
            if (instance instanceof MentalHealthNotFoundResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MentalHealthNotFoundResponse.validateJSON(instance); // throw an exception if no match
                // create MentalHealthNotFoundResponse from JS object
                this.actualInstance = MentalHealthNotFoundResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MentalHealthNotFoundResponse
            errorMessages.push("Failed to construct MentalHealthNotFoundResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `GetMentalHealthLevelOne200Response` with oneOf schemas MentalHealthData, MentalHealthNotFoundResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `GetMentalHealthLevelOne200Response` with oneOf schemas MentalHealthData, MentalHealthNotFoundResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>GetMentalHealthLevelOne200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetMentalHealthLevelOne200Response} obj Optional instance to populate.
     * @return {module:model/GetMentalHealthLevelOne200Response} The populated <code>GetMentalHealthLevelOne200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        return new GetMentalHealthLevelOne200Response(data);
    }

    /**
     * Gets the actual instance, which can be <code>MentalHealthData</code>, <code>MentalHealthNotFoundResponse</code>.
     * @return {(module:model/MentalHealthData|module:model/MentalHealthNotFoundResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MentalHealthData</code>, <code>MentalHealthNotFoundResponse</code>.
     * @param {(module:model/MentalHealthData|module:model/MentalHealthNotFoundResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = GetMentalHealthLevelOne200Response.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of GetMentalHealthLevelOne200Response from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/GetMentalHealthLevelOne200Response} An instance of GetMentalHealthLevelOne200Response.
     */
    static fromJSON = function(json_string){
        return GetMentalHealthLevelOne200Response.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} @context
 */
GetMentalHealthLevelOne200Response.prototype['@context'] = undefined;

/**
 * @member {String} @type
 */
GetMentalHealthLevelOne200Response.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
GetMentalHealthLevelOne200Response.prototype['name'] = undefined;

/**
 * @member {module:model/MentalHealthCopyrightHolder} copyrightHolder
 */
GetMentalHealthLevelOne200Response.prototype['copyrightHolder'] = undefined;

/**
 * @member {String} license
 */
GetMentalHealthLevelOne200Response.prototype['license'] = undefined;

/**
 * @member {module:model/MentalHealthAuthor} author
 */
GetMentalHealthLevelOne200Response.prototype['author'] = undefined;

/**
 * @member {module:model/MentalHealthAbout} about
 */
GetMentalHealthLevelOne200Response.prototype['about'] = undefined;

/**
 * @member {String} description
 */
GetMentalHealthLevelOne200Response.prototype['description'] = undefined;

/**
 * @member {String} url
 */
GetMentalHealthLevelOne200Response.prototype['url'] = undefined;

/**
 * @member {Array.<String>} genre
 */
GetMentalHealthLevelOne200Response.prototype['genre'] = undefined;

/**
 * @member {module:model/LivewellAboutAlternateName} keywords
 */
GetMentalHealthLevelOne200Response.prototype['keywords'] = undefined;

/**
 * @member {Date} dateModified
 */
GetMentalHealthLevelOne200Response.prototype['dateModified'] = undefined;

/**
 * @member {Array.<String>} lastReviewed
 */
GetMentalHealthLevelOne200Response.prototype['lastReviewed'] = undefined;

/**
 * @member {Array.<module:model/MentalHealthHealthTopicContent>} hasPart
 */
GetMentalHealthLevelOne200Response.prototype['hasPart'] = undefined;

/**
 * @member {module:model/MentalHealthBreadcrumb} breadcrumb
 */
GetMentalHealthLevelOne200Response.prototype['breadcrumb'] = undefined;

/**
 * @member {Array.<module:model/MentalHealthRelatedLink>} relatedLink
 */
GetMentalHealthLevelOne200Response.prototype['relatedLink'] = undefined;

/**
 * @member {String} headline
 */
GetMentalHealthLevelOne200Response.prototype['headline'] = undefined;

/**
 * @member {Array.<String>} contentSubTypes
 */
GetMentalHealthLevelOne200Response.prototype['contentSubTypes'] = undefined;

/**
 * @member {Array.<module:model/MentalHealthContentElementMainEntityOfPageInner>} mainEntityOfPage
 */
GetMentalHealthLevelOne200Response.prototype['mainEntityOfPage'] = undefined;

/**
 * @member {Array.<module:model/MentalHealthExpanderGroup>} expander_groups
 */
GetMentalHealthLevelOne200Response.prototype['expander_groups'] = undefined;

/**
 * @member {String} webpage
 */
GetMentalHealthLevelOne200Response.prototype['webpage'] = undefined;

/**
 * @member {Number} id
 */
GetMentalHealthLevelOne200Response.prototype['id'] = undefined;

/**
 * @member {String} route_mapping
 */
GetMentalHealthLevelOne200Response.prototype['route_mapping'] = undefined;

/**
 * @member {String} redirect
 */
GetMentalHealthLevelOne200Response.prototype['redirect'] = undefined;

/**
 * @member {module:model/GetMentalHealthLevelOne200Response.MessageEnum} message
 */
GetMentalHealthLevelOne200Response.prototype['message'] = undefined;

/**
 * @member {String} index of Mental Health routes
 */
GetMentalHealthLevelOne200Response.prototype['index of Mental Health routes'] = undefined;


GetMentalHealthLevelOne200Response.OneOf = ["MentalHealthData", "MentalHealthNotFoundResponse"];

export default GetMentalHealthLevelOne200Response;

