/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LivewellAboutAlternateName from './LivewellAboutAlternateName';
import PregnancyAbout from './PregnancyAbout';
import PregnancyAuthor from './PregnancyAuthor';
import PregnancyBreadcrumb from './PregnancyBreadcrumb';
import PregnancyContentElement from './PregnancyContentElement';
import PregnancyCopyrightHolder from './PregnancyCopyrightHolder';
import PregnancyData from './PregnancyData';
import PregnancyExpanderGroup from './PregnancyExpanderGroup';
import PregnancyHealthTopicContent from './PregnancyHealthTopicContent';
import PregnancyNotFoundResponse from './PregnancyNotFoundResponse';
import PregnancyRelatedLink from './PregnancyRelatedLink';

/**
 * The GetPregnancyLevelOne200Response model module.
 * @module model/GetPregnancyLevelOne200Response
 * @version 1.0.0
 */
class GetPregnancyLevelOne200Response {
    /**
     * Constructs a new <code>GetPregnancyLevelOne200Response</code>.
     * @alias module:model/GetPregnancyLevelOne200Response
     * @param {(module:model/PregnancyData|module:model/PregnancyNotFoundResponse)} instance The actual instance to initialize GetPregnancyLevelOne200Response.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof PregnancyData) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PregnancyData.validateJSON(instance); // throw an exception if no match
                // create PregnancyData from JS object
                this.actualInstance = PregnancyData.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PregnancyData
            errorMessages.push("Failed to construct PregnancyData: " + err)
        }

        try {
            if (instance instanceof PregnancyNotFoundResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PregnancyNotFoundResponse.validateJSON(instance); // throw an exception if no match
                // create PregnancyNotFoundResponse from JS object
                this.actualInstance = PregnancyNotFoundResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PregnancyNotFoundResponse
            errorMessages.push("Failed to construct PregnancyNotFoundResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `GetPregnancyLevelOne200Response` with oneOf schemas PregnancyData, PregnancyNotFoundResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `GetPregnancyLevelOne200Response` with oneOf schemas PregnancyData, PregnancyNotFoundResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>GetPregnancyLevelOne200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPregnancyLevelOne200Response} obj Optional instance to populate.
     * @return {module:model/GetPregnancyLevelOne200Response} The populated <code>GetPregnancyLevelOne200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        return new GetPregnancyLevelOne200Response(data);
    }

    /**
     * Gets the actual instance, which can be <code>PregnancyData</code>, <code>PregnancyNotFoundResponse</code>.
     * @return {(module:model/PregnancyData|module:model/PregnancyNotFoundResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>PregnancyData</code>, <code>PregnancyNotFoundResponse</code>.
     * @param {(module:model/PregnancyData|module:model/PregnancyNotFoundResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = GetPregnancyLevelOne200Response.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of GetPregnancyLevelOne200Response from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/GetPregnancyLevelOne200Response} An instance of GetPregnancyLevelOne200Response.
     */
    static fromJSON = function(json_string){
        return GetPregnancyLevelOne200Response.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} @context
 */
GetPregnancyLevelOne200Response.prototype['@context'] = undefined;

/**
 * @member {String} @type
 */
GetPregnancyLevelOne200Response.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
GetPregnancyLevelOne200Response.prototype['name'] = undefined;

/**
 * @member {module:model/PregnancyCopyrightHolder} copyrightHolder
 */
GetPregnancyLevelOne200Response.prototype['copyrightHolder'] = undefined;

/**
 * @member {String} license
 */
GetPregnancyLevelOne200Response.prototype['license'] = undefined;

/**
 * @member {module:model/PregnancyAuthor} author
 */
GetPregnancyLevelOne200Response.prototype['author'] = undefined;

/**
 * @member {module:model/PregnancyAbout} about
 */
GetPregnancyLevelOne200Response.prototype['about'] = undefined;

/**
 * @member {String} description
 */
GetPregnancyLevelOne200Response.prototype['description'] = undefined;

/**
 * Canonical content URL. An MRD API URL is normally returned by default and is rewritten where applicable when nhs_links is enabled.
 * @member {String} url
 */
GetPregnancyLevelOne200Response.prototype['url'] = undefined;

/**
 * Page genres. Pregnancy pages may return an empty array.
 * @member {Array.<String>} genre
 */
GetPregnancyLevelOne200Response.prototype['genre'] = undefined;

/**
 * @member {module:model/LivewellAboutAlternateName} keywords
 */
GetPregnancyLevelOne200Response.prototype['keywords'] = undefined;

/**
 * @member {Date} dateModified
 */
GetPregnancyLevelOne200Response.prototype['dateModified'] = undefined;

/**
 * Review date and review-due date when supplied by the source.
 * @member {Array.<String>} lastReviewed
 */
GetPregnancyLevelOne200Response.prototype['lastReviewed'] = undefined;

/**
 * Structured health-topic sections. Some category pages may return an empty array.
 * @member {Array.<module:model/PregnancyHealthTopicContent>} hasPart
 */
GetPregnancyLevelOne200Response.prototype['hasPart'] = undefined;

/**
 * @member {module:model/PregnancyBreadcrumb} breadcrumb
 */
GetPregnancyLevelOne200Response.prototype['breadcrumb'] = undefined;

/**
 * Navigation links associated with the page when supplied by the source.
 * @member {Array.<module:model/PregnancyRelatedLink>} relatedLink
 */
GetPregnancyLevelOne200Response.prototype['relatedLink'] = undefined;

/**
 * Page headline. Empty strings are valid.
 * @member {String} headline
 */
GetPregnancyLevelOne200Response.prototype['headline'] = undefined;

/**
 * @member {Array.<String>} contentSubTypes
 */
GetPregnancyLevelOne200Response.prototype['contentSubTypes'] = undefined;

/**
 * Top-level Pregnancy page content. The exact elements depend on the requested NHS page.
 * @member {Array.<module:model/PregnancyContentElement>} mainEntityOfPage
 */
GetPregnancyLevelOne200Response.prototype['mainEntityOfPage'] = undefined;

/**
 * Expandable content groups when supplied by the Pregnancy source data.
 * @member {Array.<module:model/PregnancyExpanderGroup>} expander_groups
 */
GetPregnancyLevelOne200Response.prototype['expander_groups'] = undefined;

/**
 * Original NHS webpage URL.
 * @member {String} webpage
 */
GetPregnancyLevelOne200Response.prototype['webpage'] = undefined;

/**
 * @member {Number} id
 */
GetPregnancyLevelOne200Response.prototype['id'] = undefined;

/**
 * @member {String} route_mapping
 */
GetPregnancyLevelOne200Response.prototype['route_mapping'] = undefined;

/**
 * Redirect value from the source dataset. Empty strings are valid.
 * @member {String} redirect
 */
GetPregnancyLevelOne200Response.prototype['redirect'] = undefined;

/**
 * @member {module:model/GetPregnancyLevelOne200Response.MessageEnum} message
 */
GetPregnancyLevelOne200Response.prototype['message'] = undefined;

/**
 * @member {String} index of Pregnancy routes
 */
GetPregnancyLevelOne200Response.prototype['index of Pregnancy routes'] = undefined;


GetPregnancyLevelOne200Response.OneOf = ["PregnancyData", "PregnancyNotFoundResponse"];

export default GetPregnancyLevelOne200Response;

