/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConditionVideoObjectIdentifier from './ConditionVideoObjectIdentifier';
import LivewellAnswer from './LivewellAnswer';
import LivewellAnswerLinksInner from './LivewellAnswerLinksInner';
import LivewellContentElement from './LivewellContentElement';
import LivewellVideoObject from './LivewellVideoObject';

/**
 * The LivewellContentElementMainEntityInner model module.
 * @module model/LivewellContentElementMainEntityInner
 * @version 1.0.0
 */
class LivewellContentElementMainEntityInner {
    /**
     * Constructs a new <code>LivewellContentElementMainEntityInner</code>.
     * @alias module:model/LivewellContentElementMainEntityInner
     * @param {(module:model/LivewellContentElement|module:model/LivewellVideoObject)} instance The actual instance to initialize LivewellContentElementMainEntityInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof LivewellContentElement) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                LivewellContentElement.validateJSON(instance); // throw an exception if no match
                // create LivewellContentElement from JS object
                this.actualInstance = LivewellContentElement.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into LivewellContentElement
            errorMessages.push("Failed to construct LivewellContentElement: " + err)
        }

        try {
            if (instance instanceof LivewellVideoObject) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                LivewellVideoObject.validateJSON(instance); // throw an exception if no match
                // create LivewellVideoObject from JS object
                this.actualInstance = LivewellVideoObject.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into LivewellVideoObject
            errorMessages.push("Failed to construct LivewellVideoObject: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `LivewellContentElementMainEntityInner` with oneOf schemas LivewellContentElement, LivewellVideoObject. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `LivewellContentElementMainEntityInner` with oneOf schemas LivewellContentElement, LivewellVideoObject. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>LivewellContentElementMainEntityInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LivewellContentElementMainEntityInner} obj Optional instance to populate.
     * @return {module:model/LivewellContentElementMainEntityInner} The populated <code>LivewellContentElementMainEntityInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new LivewellContentElementMainEntityInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>LivewellContentElement</code>, <code>LivewellVideoObject</code>.
     * @return {(module:model/LivewellContentElement|module:model/LivewellVideoObject)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>LivewellContentElement</code>, <code>LivewellVideoObject</code>.
     * @param {(module:model/LivewellContentElement|module:model/LivewellVideoObject)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = LivewellContentElementMainEntityInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of LivewellContentElementMainEntityInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/LivewellContentElementMainEntityInner} An instance of LivewellContentElementMainEntityInner.
     */
    static fromJSON = function(json_string){
        return LivewellContentElementMainEntityInner.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} @type
 */
LivewellContentElementMainEntityInner.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
LivewellContentElementMainEntityInner.prototype['name'] = undefined;

/**
 * @member {module:model/ConditionVideoObjectIdentifier} identifier
 */
LivewellContentElementMainEntityInner.prototype['identifier'] = undefined;

/**
 * @member {Number} position
 */
LivewellContentElementMainEntityInner.prototype['position'] = undefined;

/**
 * @member {String} headline
 */
LivewellContentElementMainEntityInner.prototype['headline'] = undefined;

/**
 * @member {String} description
 */
LivewellContentElementMainEntityInner.prototype['description'] = undefined;

/**
 * @member {String} url
 */
LivewellContentElementMainEntityInner.prototype['url'] = undefined;

/**
 * Rendered video HTML or processed plain text.
 * @member {String} text
 */
LivewellContentElementMainEntityInner.prototype['text'] = undefined;

/**
 * @member {Array.<module:model/LivewellAnswerLinksInner>} links
 */
LivewellContentElementMainEntityInner.prototype['links'] = undefined;

/**
 * @member {module:model/LivewellAnswer} acceptedAnswer
 */
LivewellContentElementMainEntityInner.prototype['acceptedAnswer'] = undefined;

/**
 * @member {Array.<module:model/LivewellContentElementMainEntityInner>} mainEntity
 */
LivewellContentElementMainEntityInner.prototype['mainEntity'] = undefined;

/**
 * @member {Array.<module:model/LivewellContentElementMainEntityInner>} mainEntityOfPage
 */
LivewellContentElementMainEntityInner.prototype['mainEntityOfPage'] = undefined;

/**
 * @member {Array.<module:model/LivewellContentElementMainEntityInner>} hasPart
 */
LivewellContentElementMainEntityInner.prototype['hasPart'] = undefined;

/**
 * @member {String} embedUrl
 */
LivewellContentElementMainEntityInner.prototype['embedUrl'] = undefined;

/**
 * @member {String} contentUrl
 */
LivewellContentElementMainEntityInner.prototype['contentUrl'] = undefined;

/**
 * @member {String} duration
 */
LivewellContentElementMainEntityInner.prototype['duration'] = undefined;

/**
 * @member {String} alternateName
 */
LivewellContentElementMainEntityInner.prototype['alternateName'] = undefined;

/**
 * @member {Date} uploadDate
 */
LivewellContentElementMainEntityInner.prototype['uploadDate'] = undefined;

/**
 * @member {Array.<String>} lastReviewed
 */
LivewellContentElementMainEntityInner.prototype['lastReviewed'] = undefined;

/**
 * @member {String} thumbnailUrl
 */
LivewellContentElementMainEntityInner.prototype['thumbnailUrl'] = undefined;


LivewellContentElementMainEntityInner.OneOf = ["LivewellContentElement", "LivewellVideoObject"];

export default LivewellContentElementMainEntityInner;

