/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LivewellAnswerLinksInner from './LivewellAnswerLinksInner';

/**
 * The LivewellExpanderItem model module.
 * @module model/LivewellExpanderItem
 * @version 1.0.0
 */
class LivewellExpanderItem {
    /**
     * Constructs a new <code>LivewellExpanderItem</code>.
     * @alias module:model/LivewellExpanderItem
     */
    constructor() { 
        
        LivewellExpanderItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LivewellExpanderItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LivewellExpanderItem} obj Optional instance to populate.
     * @return {module:model/LivewellExpanderItem} The populated <code>LivewellExpanderItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LivewellExpanderItem();

            if (data.hasOwnProperty('heading')) {
                obj['heading'] = ApiClient.convertToType(data['heading'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [LivewellAnswerLinksInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LivewellExpanderItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LivewellExpanderItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['heading'] && !(typeof data['heading'] === 'string' || data['heading'] instanceof String)) {
            throw new Error("Expected the field `heading` to be a primitive type in the JSON string but got " + data['heading']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                LivewellAnswerLinksInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} heading
 */
LivewellExpanderItem.prototype['heading'] = undefined;

/**
 * @member {String} content
 */
LivewellExpanderItem.prototype['content'] = undefined;

/**
 * @member {Array.<module:model/LivewellAnswerLinksInner>} links
 */
LivewellExpanderItem.prototype['links'] = undefined;






export default LivewellExpanderItem;

