/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LivewellRoutesResponse model module.
 * @module model/LivewellRoutesResponse
 * @version 1.0.0
 */
class LivewellRoutesResponse {
    /**
     * Constructs a new <code>LivewellRoutesResponse</code>.
     * Available routes within the Live Well service.
     * @alias module:model/LivewellRoutesResponse
     * @param routes {Array.<String>} 
     */
    constructor(routes) { 
        
        LivewellRoutesResponse.initialize(this, routes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, routes) { 
        obj['routes'] = routes;
    }

    /**
     * Constructs a <code>LivewellRoutesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LivewellRoutesResponse} obj Optional instance to populate.
     * @return {module:model/LivewellRoutesResponse} The populated <code>LivewellRoutesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LivewellRoutesResponse();

            if (data.hasOwnProperty('routes')) {
                obj['routes'] = ApiClient.convertToType(data['routes'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LivewellRoutesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LivewellRoutesResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LivewellRoutesResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['routes'])) {
            throw new Error("Expected the field `routes` to be an array in the JSON data but got " + data['routes']);
        }

        return true;
    }


}

LivewellRoutesResponse.RequiredProperties = ["routes"];

/**
 * @member {Array.<String>} routes
 */
LivewellRoutesResponse.prototype['routes'] = undefined;






export default LivewellRoutesResponse;

