/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LivewellLinkObject model module.
 * @module model/LivewellLinkObject
 * @version 1.0.0
 */
class LivewellLinkObject {
    /**
     * Constructs a new <code>LivewellLinkObject</code>.
     * A link extracted or rewritten by the Live Well content processor.
     * @alias module:model/LivewellLinkObject
     */
    constructor() { 
        
        LivewellLinkObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LivewellLinkObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LivewellLinkObject} obj Optional instance to populate.
     * @return {module:model/LivewellLinkObject} The populated <code>LivewellLinkObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LivewellLinkObject();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('mrd_api_link')) {
                obj['mrd_api_link'] = ApiClient.convertToType(data['mrd_api_link'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LivewellLinkObject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LivewellLinkObject</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['mrd_api_link'] && !(typeof data['mrd_api_link'] === 'string' || data['mrd_api_link'] instanceof String)) {
            throw new Error("Expected the field `mrd_api_link` to be a primitive type in the JSON string but got " + data['mrd_api_link']);
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }

        return true;
    }


}



/**
 * @member {String} key
 */
LivewellLinkObject.prototype['key'] = undefined;

/**
 * @member {String} mrd_api_link
 */
LivewellLinkObject.prototype['mrd_api_link'] = undefined;

/**
 * @member {String} link
 */
LivewellLinkObject.prototype['link'] = undefined;






export default LivewellLinkObject;

