/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LivewellAboutAlternateName from './LivewellAboutAlternateName';

/**
 * The LivewellAbout model module.
 * @module model/LivewellAbout
 * @version 1.0.0
 */
class LivewellAbout {
    /**
     * Constructs a new <code>LivewellAbout</code>.
     * @alias module:model/LivewellAbout
     */
    constructor() { 
        
        LivewellAbout.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LivewellAbout</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LivewellAbout} obj Optional instance to populate.
     * @return {module:model/LivewellAbout} The populated <code>LivewellAbout</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LivewellAbout();

            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('alternateName')) {
                obj['alternateName'] = LivewellAboutAlternateName.constructFromObject(data['alternateName']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LivewellAbout</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LivewellAbout</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `alternateName`
        if (data['alternateName']) { // data not null
          LivewellAboutAlternateName.validateJSON(data['alternateName']);
        }

        return true;
    }


}



/**
 * @member {String} @type
 */
LivewellAbout.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
LivewellAbout.prototype['name'] = undefined;

/**
 * @member {module:model/LivewellAboutAlternateName} alternateName
 */
LivewellAbout.prototype['alternateName'] = undefined;






export default LivewellAbout;

