/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementBodyTemperatureLocation from './MeasurementBodyTemperatureLocation';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementBodyTemperatureLocationResult model module.
 * @module model/MeasurementBodyTemperatureLocationResult
 * @version 1.0.0
 */
class MeasurementBodyTemperatureLocationResult {
    /**
     * Constructs a new <code>MeasurementBodyTemperatureLocationResult</code>.
     * Body temperature location or an application-level error object.
     * @alias module:model/MeasurementBodyTemperatureLocationResult
     * @param {(module:model/MeasurementBodyTemperatureLocation|module:model/MeasurementsErrorResponse)} instance The actual instance to initialize MeasurementBodyTemperatureLocationResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MeasurementBodyTemperatureLocation) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementBodyTemperatureLocation.validateJSON(instance); // throw an exception if no match
                // create MeasurementBodyTemperatureLocation from JS object
                this.actualInstance = MeasurementBodyTemperatureLocation.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementBodyTemperatureLocation
            errorMessages.push("Failed to construct MeasurementBodyTemperatureLocation: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementBodyTemperatureLocationResult` with oneOf schemas MeasurementBodyTemperatureLocation, MeasurementsErrorResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementBodyTemperatureLocationResult` with oneOf schemas MeasurementBodyTemperatureLocation, MeasurementsErrorResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementBodyTemperatureLocationResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementBodyTemperatureLocationResult} obj Optional instance to populate.
     * @return {module:model/MeasurementBodyTemperatureLocationResult} The populated <code>MeasurementBodyTemperatureLocationResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementBodyTemperatureLocationResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementBodyTemperatureLocation</code>, <code>MeasurementsErrorResponse</code>.
     * @return {(module:model/MeasurementBodyTemperatureLocation|module:model/MeasurementsErrorResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementBodyTemperatureLocation</code>, <code>MeasurementsErrorResponse</code>.
     * @param {(module:model/MeasurementBodyTemperatureLocation|module:model/MeasurementsErrorResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementBodyTemperatureLocationResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementBodyTemperatureLocationResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementBodyTemperatureLocationResult} An instance of MeasurementBodyTemperatureLocationResult.
     */
    static fromJSON = function(json_string){
        return MeasurementBodyTemperatureLocationResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} id
 */
MeasurementBodyTemperatureLocationResult.prototype['id'] = undefined;

/**
 * @member {String} body_temperature_location_id
 */
MeasurementBodyTemperatureLocationResult.prototype['body_temperature_location_id'] = undefined;

/**
 * @member {String} description
 */
MeasurementBodyTemperatureLocationResult.prototype['description'] = undefined;

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementBodyTemperatureLocationResult.prototype['error'] = undefined;


MeasurementBodyTemperatureLocationResult.OneOf = ["MeasurementBodyTemperatureLocation", "MeasurementsErrorResponse"];

export default MeasurementBodyTemperatureLocationResult;

