/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MeasurementExerciseType model module.
 * @module model/MeasurementExerciseType
 * @version 1.0.0
 */
class MeasurementExerciseType {
    /**
     * Constructs a new <code>MeasurementExerciseType</code>.
     * Exercise type lookup record.
     * @alias module:model/MeasurementExerciseType
     * @param id {String} 
     * @param exerciseTypeName {String} 
     * @param description {String} 
     */
    constructor(id, exerciseTypeName, description) { 
        
        MeasurementExerciseType.initialize(this, id, exerciseTypeName, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, exerciseTypeName, description) { 
        obj['id'] = id;
        obj['exercise_type_name'] = exerciseTypeName;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>MeasurementExerciseType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementExerciseType} obj Optional instance to populate.
     * @return {module:model/MeasurementExerciseType} The populated <code>MeasurementExerciseType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MeasurementExerciseType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('exercise_type_name')) {
                obj['exercise_type_name'] = ApiClient.convertToType(data['exercise_type_name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MeasurementExerciseType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MeasurementExerciseType</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MeasurementExerciseType.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['exercise_type_name'] && !(typeof data['exercise_type_name'] === 'string' || data['exercise_type_name'] instanceof String)) {
            throw new Error("Expected the field `exercise_type_name` to be a primitive type in the JSON string but got " + data['exercise_type_name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

MeasurementExerciseType.RequiredProperties = ["id", "exercise_type_name", "description"];

/**
 * @member {String} id
 */
MeasurementExerciseType.prototype['id'] = undefined;

/**
 * @member {String} exercise_type_name
 */
MeasurementExerciseType.prototype['exercise_type_name'] = undefined;

/**
 * @member {String} description
 */
MeasurementExerciseType.prototype['description'] = undefined;






export default MeasurementExerciseType;

