/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementGroup from './MeasurementGroup';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementGroupResult model module.
 * @module model/MeasurementGroupResult
 * @version 1.0.0
 */
class MeasurementGroupResult {
    /**
     * Constructs a new <code>MeasurementGroupResult</code>.
     * Measurement group or an application-level error object.
     * @alias module:model/MeasurementGroupResult
     * @param {(module:model/MeasurementGroup|module:model/MeasurementsErrorResponse)} instance The actual instance to initialize MeasurementGroupResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MeasurementGroup) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementGroup.validateJSON(instance); // throw an exception if no match
                // create MeasurementGroup from JS object
                this.actualInstance = MeasurementGroup.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementGroup
            errorMessages.push("Failed to construct MeasurementGroup: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementGroupResult` with oneOf schemas MeasurementGroup, MeasurementsErrorResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementGroupResult` with oneOf schemas MeasurementGroup, MeasurementsErrorResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementGroupResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementGroupResult} obj Optional instance to populate.
     * @return {module:model/MeasurementGroupResult} The populated <code>MeasurementGroupResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementGroupResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementGroup</code>, <code>MeasurementsErrorResponse</code>.
     * @return {(module:model/MeasurementGroup|module:model/MeasurementsErrorResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementGroup</code>, <code>MeasurementsErrorResponse</code>.
     * @param {(module:model/MeasurementGroup|module:model/MeasurementsErrorResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementGroupResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementGroupResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementGroupResult} An instance of MeasurementGroupResult.
     */
    static fromJSON = function(json_string){
        return MeasurementGroupResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} id
 */
MeasurementGroupResult.prototype['id'] = undefined;

/**
 * @member {String} measurement_group_name
 */
MeasurementGroupResult.prototype['measurement_group_name'] = undefined;

/**
 * @member {String} measurement_group_definition
 */
MeasurementGroupResult.prototype['measurement_group_definition'] = undefined;

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementGroupResult.prototype['error'] = undefined;


MeasurementGroupResult.OneOf = ["MeasurementGroup", "MeasurementsErrorResponse"];

export default MeasurementGroupResult;

