/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementGroup from './MeasurementGroup';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementGroupsResult model module.
 * @module model/MeasurementGroupsResult
 * @version 1.0.0
 */
class MeasurementGroupsResult {
    /**
     * Constructs a new <code>MeasurementGroupsResult</code>.
     * Available measurement groups or an application-level error object.
     * @alias module:model/MeasurementGroupsResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementGroup])} instance The actual instance to initialize MeasurementGroupsResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available measurement groups.
        try {
            if (instance instanceof [MeasurementGroup]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementGroup].validateJSON(instance); // throw an exception if no match
                // create [MeasurementGroup] from JS object
                this.actualInstance = [MeasurementGroup].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementGroup]
            errorMessages.push("Failed to construct [MeasurementGroup]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementGroupsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementGroup]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementGroupsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementGroup]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementGroupsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementGroupsResult} obj Optional instance to populate.
     * @return {module:model/MeasurementGroupsResult} The populated <code>MeasurementGroupsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementGroupsResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementGroup]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementGroup])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementGroup]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementGroup])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementGroupsResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementGroupsResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementGroupsResult} An instance of MeasurementGroupsResult.
     */
    static fromJSON = function(json_string){
        return MeasurementGroupsResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementGroupsResult.prototype['error'] = undefined;


MeasurementGroupsResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementGroup]"];

export default MeasurementGroupsResult;

