/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementCervicalMucusTexture from './MeasurementCervicalMucusTexture';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementCervicalMucusTexturesResult model module.
 * @module model/MeasurementCervicalMucusTexturesResult
 * @version 1.0.0
 */
class MeasurementCervicalMucusTexturesResult {
    /**
     * Constructs a new <code>MeasurementCervicalMucusTexturesResult</code>.
     * Available cervical mucus textures or an application-level error object.
     * @alias module:model/MeasurementCervicalMucusTexturesResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalMucusTexture])} instance The actual instance to initialize MeasurementCervicalMucusTexturesResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available cervical mucus textures.
        try {
            if (instance instanceof [MeasurementCervicalMucusTexture]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementCervicalMucusTexture].validateJSON(instance); // throw an exception if no match
                // create [MeasurementCervicalMucusTexture] from JS object
                this.actualInstance = [MeasurementCervicalMucusTexture].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementCervicalMucusTexture]
            errorMessages.push("Failed to construct [MeasurementCervicalMucusTexture]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementCervicalMucusTexturesResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementCervicalMucusTexture]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementCervicalMucusTexturesResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementCervicalMucusTexture]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementCervicalMucusTexturesResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementCervicalMucusTexturesResult} obj Optional instance to populate.
     * @return {module:model/MeasurementCervicalMucusTexturesResult} The populated <code>MeasurementCervicalMucusTexturesResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementCervicalMucusTexturesResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementCervicalMucusTexture]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalMucusTexture])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementCervicalMucusTexture]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalMucusTexture])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementCervicalMucusTexturesResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementCervicalMucusTexturesResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementCervicalMucusTexturesResult} An instance of MeasurementCervicalMucusTexturesResult.
     */
    static fromJSON = function(json_string){
        return MeasurementCervicalMucusTexturesResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementCervicalMucusTexturesResult.prototype['error'] = undefined;


MeasurementCervicalMucusTexturesResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementCervicalMucusTexture]"];

export default MeasurementCervicalMucusTexturesResult;

