/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementExerciseType from './MeasurementExerciseType';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementExerciseTypeResult model module.
 * @module model/MeasurementExerciseTypeResult
 * @version 1.0.0
 */
class MeasurementExerciseTypeResult {
    /**
     * Constructs a new <code>MeasurementExerciseTypeResult</code>.
     * Exercise type or an application-level error object.
     * @alias module:model/MeasurementExerciseTypeResult
     * @param {(module:model/MeasurementExerciseType|module:model/MeasurementsErrorResponse)} instance The actual instance to initialize MeasurementExerciseTypeResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MeasurementExerciseType) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementExerciseType.validateJSON(instance); // throw an exception if no match
                // create MeasurementExerciseType from JS object
                this.actualInstance = MeasurementExerciseType.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementExerciseType
            errorMessages.push("Failed to construct MeasurementExerciseType: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementExerciseTypeResult` with oneOf schemas MeasurementExerciseType, MeasurementsErrorResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementExerciseTypeResult` with oneOf schemas MeasurementExerciseType, MeasurementsErrorResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementExerciseTypeResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementExerciseTypeResult} obj Optional instance to populate.
     * @return {module:model/MeasurementExerciseTypeResult} The populated <code>MeasurementExerciseTypeResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementExerciseTypeResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementExerciseType</code>, <code>MeasurementsErrorResponse</code>.
     * @return {(module:model/MeasurementExerciseType|module:model/MeasurementsErrorResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementExerciseType</code>, <code>MeasurementsErrorResponse</code>.
     * @param {(module:model/MeasurementExerciseType|module:model/MeasurementsErrorResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementExerciseTypeResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementExerciseTypeResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementExerciseTypeResult} An instance of MeasurementExerciseTypeResult.
     */
    static fromJSON = function(json_string){
        return MeasurementExerciseTypeResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} id
 */
MeasurementExerciseTypeResult.prototype['id'] = undefined;

/**
 * @member {String} exercise_type_name
 */
MeasurementExerciseTypeResult.prototype['exercise_type_name'] = undefined;

/**
 * @member {String} description
 */
MeasurementExerciseTypeResult.prototype['description'] = undefined;

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementExerciseTypeResult.prototype['error'] = undefined;


MeasurementExerciseTypeResult.OneOf = ["MeasurementExerciseType", "MeasurementsErrorResponse"];

export default MeasurementExerciseTypeResult;

