/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementTemporalRelationToMeal from './MeasurementTemporalRelationToMeal';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementTemporalRelationToMealResult model module.
 * @module model/MeasurementTemporalRelationToMealResult
 * @version 1.0.0
 */
class MeasurementTemporalRelationToMealResult {
    /**
     * Constructs a new <code>MeasurementTemporalRelationToMealResult</code>.
     * Temporal relation to meal or an application-level error object.
     * @alias module:model/MeasurementTemporalRelationToMealResult
     * @param {(module:model/MeasurementTemporalRelationToMeal|module:model/MeasurementsErrorResponse)} instance The actual instance to initialize MeasurementTemporalRelationToMealResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MeasurementTemporalRelationToMeal) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementTemporalRelationToMeal.validateJSON(instance); // throw an exception if no match
                // create MeasurementTemporalRelationToMeal from JS object
                this.actualInstance = MeasurementTemporalRelationToMeal.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementTemporalRelationToMeal
            errorMessages.push("Failed to construct MeasurementTemporalRelationToMeal: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementTemporalRelationToMealResult` with oneOf schemas MeasurementTemporalRelationToMeal, MeasurementsErrorResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementTemporalRelationToMealResult` with oneOf schemas MeasurementTemporalRelationToMeal, MeasurementsErrorResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementTemporalRelationToMealResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementTemporalRelationToMealResult} obj Optional instance to populate.
     * @return {module:model/MeasurementTemporalRelationToMealResult} The populated <code>MeasurementTemporalRelationToMealResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementTemporalRelationToMealResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementTemporalRelationToMeal</code>, <code>MeasurementsErrorResponse</code>.
     * @return {(module:model/MeasurementTemporalRelationToMeal|module:model/MeasurementsErrorResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementTemporalRelationToMeal</code>, <code>MeasurementsErrorResponse</code>.
     * @param {(module:model/MeasurementTemporalRelationToMeal|module:model/MeasurementsErrorResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementTemporalRelationToMealResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementTemporalRelationToMealResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementTemporalRelationToMealResult} An instance of MeasurementTemporalRelationToMealResult.
     */
    static fromJSON = function(json_string){
        return MeasurementTemporalRelationToMealResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} id
 */
MeasurementTemporalRelationToMealResult.prototype['id'] = undefined;

/**
 * @member {String} temporal_relation_to_meal_id
 */
MeasurementTemporalRelationToMealResult.prototype['temporal_relation_to_meal_id'] = undefined;

/**
 * @member {String} description
 */
MeasurementTemporalRelationToMealResult.prototype['description'] = undefined;

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementTemporalRelationToMealResult.prototype['error'] = undefined;


MeasurementTemporalRelationToMealResult.OneOf = ["MeasurementTemporalRelationToMeal", "MeasurementsErrorResponse"];

export default MeasurementTemporalRelationToMealResult;

