/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementActivityType from './MeasurementActivityType';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementActivityTypesResult model module.
 * @module model/MeasurementActivityTypesResult
 * @version 1.0.0
 */
class MeasurementActivityTypesResult {
    /**
     * Constructs a new <code>MeasurementActivityTypesResult</code>.
     * Available activity types or an application-level error object.
     * @alias module:model/MeasurementActivityTypesResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementActivityType])} instance The actual instance to initialize MeasurementActivityTypesResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available activity types.
        try {
            if (instance instanceof [MeasurementActivityType]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementActivityType].validateJSON(instance); // throw an exception if no match
                // create [MeasurementActivityType] from JS object
                this.actualInstance = [MeasurementActivityType].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementActivityType]
            errorMessages.push("Failed to construct [MeasurementActivityType]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementActivityTypesResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementActivityType]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementActivityTypesResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementActivityType]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementActivityTypesResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementActivityTypesResult} obj Optional instance to populate.
     * @return {module:model/MeasurementActivityTypesResult} The populated <code>MeasurementActivityTypesResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementActivityTypesResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementActivityType]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementActivityType])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementActivityType]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementActivityType])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementActivityTypesResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementActivityTypesResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementActivityTypesResult} An instance of MeasurementActivityTypesResult.
     */
    static fromJSON = function(json_string){
        return MeasurementActivityTypesResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementActivityTypesResult.prototype['error'] = undefined;


MeasurementActivityTypesResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementActivityType]"];

export default MeasurementActivityTypesResult;

