/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementCervicalDilation from './MeasurementCervicalDilation';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementCervicalDilationsResult model module.
 * @module model/MeasurementCervicalDilationsResult
 * @version 1.0.0
 */
class MeasurementCervicalDilationsResult {
    /**
     * Constructs a new <code>MeasurementCervicalDilationsResult</code>.
     * Available cervical dilations or an application-level error object.
     * @alias module:model/MeasurementCervicalDilationsResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalDilation])} instance The actual instance to initialize MeasurementCervicalDilationsResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available cervical dilations.
        try {
            if (instance instanceof [MeasurementCervicalDilation]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementCervicalDilation].validateJSON(instance); // throw an exception if no match
                // create [MeasurementCervicalDilation] from JS object
                this.actualInstance = [MeasurementCervicalDilation].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementCervicalDilation]
            errorMessages.push("Failed to construct [MeasurementCervicalDilation]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementCervicalDilationsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementCervicalDilation]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementCervicalDilationsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementCervicalDilation]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementCervicalDilationsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementCervicalDilationsResult} obj Optional instance to populate.
     * @return {module:model/MeasurementCervicalDilationsResult} The populated <code>MeasurementCervicalDilationsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementCervicalDilationsResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementCervicalDilation]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalDilation])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementCervicalDilation]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalDilation])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementCervicalDilationsResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementCervicalDilationsResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementCervicalDilationsResult} An instance of MeasurementCervicalDilationsResult.
     */
    static fromJSON = function(json_string){
        return MeasurementCervicalDilationsResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementCervicalDilationsResult.prototype['error'] = undefined;


MeasurementCervicalDilationsResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementCervicalDilation]"];

export default MeasurementCervicalDilationsResult;

