/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementCervicalPosition from './MeasurementCervicalPosition';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementCervicalPositionResult model module.
 * @module model/MeasurementCervicalPositionResult
 * @version 1.0.0
 */
class MeasurementCervicalPositionResult {
    /**
     * Constructs a new <code>MeasurementCervicalPositionResult</code>.
     * Cervical position or an application-level error object.
     * @alias module:model/MeasurementCervicalPositionResult
     * @param {(module:model/MeasurementCervicalPosition|module:model/MeasurementsErrorResponse)} instance The actual instance to initialize MeasurementCervicalPositionResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MeasurementCervicalPosition) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementCervicalPosition.validateJSON(instance); // throw an exception if no match
                // create MeasurementCervicalPosition from JS object
                this.actualInstance = MeasurementCervicalPosition.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementCervicalPosition
            errorMessages.push("Failed to construct MeasurementCervicalPosition: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementCervicalPositionResult` with oneOf schemas MeasurementCervicalPosition, MeasurementsErrorResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementCervicalPositionResult` with oneOf schemas MeasurementCervicalPosition, MeasurementsErrorResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementCervicalPositionResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementCervicalPositionResult} obj Optional instance to populate.
     * @return {module:model/MeasurementCervicalPositionResult} The populated <code>MeasurementCervicalPositionResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementCervicalPositionResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementCervicalPosition</code>, <code>MeasurementsErrorResponse</code>.
     * @return {(module:model/MeasurementCervicalPosition|module:model/MeasurementsErrorResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementCervicalPosition</code>, <code>MeasurementsErrorResponse</code>.
     * @param {(module:model/MeasurementCervicalPosition|module:model/MeasurementsErrorResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementCervicalPositionResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementCervicalPositionResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementCervicalPositionResult} An instance of MeasurementCervicalPositionResult.
     */
    static fromJSON = function(json_string){
        return MeasurementCervicalPositionResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} id
 */
MeasurementCervicalPositionResult.prototype['id'] = undefined;

/**
 * @member {String} cervical_position_id
 */
MeasurementCervicalPositionResult.prototype['cervical_position_id'] = undefined;

/**
 * @member {String} description
 */
MeasurementCervicalPositionResult.prototype['description'] = undefined;

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementCervicalPositionResult.prototype['error'] = undefined;


MeasurementCervicalPositionResult.OneOf = ["MeasurementCervicalPosition", "MeasurementsErrorResponse"];

export default MeasurementCervicalPositionResult;

