/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementBodyPosition from './MeasurementBodyPosition';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementBodyPositionsResult model module.
 * @module model/MeasurementBodyPositionsResult
 * @version 1.0.0
 */
class MeasurementBodyPositionsResult {
    /**
     * Constructs a new <code>MeasurementBodyPositionsResult</code>.
     * Available body positions or an application-level error object.
     * @alias module:model/MeasurementBodyPositionsResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementBodyPosition])} instance The actual instance to initialize MeasurementBodyPositionsResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available body positions.
        try {
            if (instance instanceof [MeasurementBodyPosition]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementBodyPosition].validateJSON(instance); // throw an exception if no match
                // create [MeasurementBodyPosition] from JS object
                this.actualInstance = [MeasurementBodyPosition].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementBodyPosition]
            errorMessages.push("Failed to construct [MeasurementBodyPosition]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementBodyPositionsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementBodyPosition]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementBodyPositionsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementBodyPosition]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementBodyPositionsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementBodyPositionsResult} obj Optional instance to populate.
     * @return {module:model/MeasurementBodyPositionsResult} The populated <code>MeasurementBodyPositionsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementBodyPositionsResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementBodyPosition]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementBodyPosition])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementBodyPosition]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementBodyPosition])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementBodyPositionsResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementBodyPositionsResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementBodyPositionsResult} An instance of MeasurementBodyPositionsResult.
     */
    static fromJSON = function(json_string){
        return MeasurementBodyPositionsResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementBodyPositionsResult.prototype['error'] = undefined;


MeasurementBodyPositionsResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementBodyPosition]"];

export default MeasurementBodyPositionsResult;

