/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementTemporalRelationToMeal from './MeasurementTemporalRelationToMeal';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementTemporalRelationsToMealResult model module.
 * @module model/MeasurementTemporalRelationsToMealResult
 * @version 1.0.0
 */
class MeasurementTemporalRelationsToMealResult {
    /**
     * Constructs a new <code>MeasurementTemporalRelationsToMealResult</code>.
     * Available temporal relations to meals or an application-level error object.
     * @alias module:model/MeasurementTemporalRelationsToMealResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementTemporalRelationToMeal])} instance The actual instance to initialize MeasurementTemporalRelationsToMealResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available temporal relations to meals.
        try {
            if (instance instanceof [MeasurementTemporalRelationToMeal]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementTemporalRelationToMeal].validateJSON(instance); // throw an exception if no match
                // create [MeasurementTemporalRelationToMeal] from JS object
                this.actualInstance = [MeasurementTemporalRelationToMeal].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementTemporalRelationToMeal]
            errorMessages.push("Failed to construct [MeasurementTemporalRelationToMeal]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementTemporalRelationsToMealResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementTemporalRelationToMeal]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementTemporalRelationsToMealResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementTemporalRelationToMeal]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementTemporalRelationsToMealResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementTemporalRelationsToMealResult} obj Optional instance to populate.
     * @return {module:model/MeasurementTemporalRelationsToMealResult} The populated <code>MeasurementTemporalRelationsToMealResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementTemporalRelationsToMealResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementTemporalRelationToMeal]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementTemporalRelationToMeal])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementTemporalRelationToMeal]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementTemporalRelationToMeal])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementTemporalRelationsToMealResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementTemporalRelationsToMealResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementTemporalRelationsToMealResult} An instance of MeasurementTemporalRelationsToMealResult.
     */
    static fromJSON = function(json_string){
        return MeasurementTemporalRelationsToMealResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementTemporalRelationsToMealResult.prototype['error'] = undefined;


MeasurementTemporalRelationsToMealResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementTemporalRelationToMeal]"];

export default MeasurementTemporalRelationsToMealResult;

