/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementCervicalPosition from './MeasurementCervicalPosition';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementCervicalPositionsResult model module.
 * @module model/MeasurementCervicalPositionsResult
 * @version 1.0.0
 */
class MeasurementCervicalPositionsResult {
    /**
     * Constructs a new <code>MeasurementCervicalPositionsResult</code>.
     * Available cervical positions or an application-level error object.
     * @alias module:model/MeasurementCervicalPositionsResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalPosition])} instance The actual instance to initialize MeasurementCervicalPositionsResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available cervical positions.
        try {
            if (instance instanceof [MeasurementCervicalPosition]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementCervicalPosition].validateJSON(instance); // throw an exception if no match
                // create [MeasurementCervicalPosition] from JS object
                this.actualInstance = [MeasurementCervicalPosition].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementCervicalPosition]
            errorMessages.push("Failed to construct [MeasurementCervicalPosition]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementCervicalPositionsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementCervicalPosition]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementCervicalPositionsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementCervicalPosition]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementCervicalPositionsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementCervicalPositionsResult} obj Optional instance to populate.
     * @return {module:model/MeasurementCervicalPositionsResult} The populated <code>MeasurementCervicalPositionsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementCervicalPositionsResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementCervicalPosition]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalPosition])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementCervicalPosition]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementCervicalPosition])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementCervicalPositionsResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementCervicalPositionsResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementCervicalPositionsResult} An instance of MeasurementCervicalPositionsResult.
     */
    static fromJSON = function(json_string){
        return MeasurementCervicalPositionsResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementCervicalPositionsResult.prototype['error'] = undefined;


MeasurementCervicalPositionsResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementCervicalPosition]"];

export default MeasurementCervicalPositionsResult;

