/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementSleepSegmentType from './MeasurementSleepSegmentType';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementSleepSegmentTypesResult model module.
 * @module model/MeasurementSleepSegmentTypesResult
 * @version 1.0.0
 */
class MeasurementSleepSegmentTypesResult {
    /**
     * Constructs a new <code>MeasurementSleepSegmentTypesResult</code>.
     * Available sleep segment types or an application-level error object.
     * @alias module:model/MeasurementSleepSegmentTypesResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementSleepSegmentType])} instance The actual instance to initialize MeasurementSleepSegmentTypesResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available sleep segment types.
        try {
            if (instance instanceof [MeasurementSleepSegmentType]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementSleepSegmentType].validateJSON(instance); // throw an exception if no match
                // create [MeasurementSleepSegmentType] from JS object
                this.actualInstance = [MeasurementSleepSegmentType].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementSleepSegmentType]
            errorMessages.push("Failed to construct [MeasurementSleepSegmentType]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementSleepSegmentTypesResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementSleepSegmentType]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementSleepSegmentTypesResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementSleepSegmentType]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementSleepSegmentTypesResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementSleepSegmentTypesResult} obj Optional instance to populate.
     * @return {module:model/MeasurementSleepSegmentTypesResult} The populated <code>MeasurementSleepSegmentTypesResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementSleepSegmentTypesResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementSleepSegmentType]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementSleepSegmentType])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementSleepSegmentType]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementSleepSegmentType])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementSleepSegmentTypesResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementSleepSegmentTypesResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementSleepSegmentTypesResult} An instance of MeasurementSleepSegmentTypesResult.
     */
    static fromJSON = function(json_string){
        return MeasurementSleepSegmentTypesResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementSleepSegmentTypesResult.prototype['error'] = undefined;


MeasurementSleepSegmentTypesResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementSleepSegmentType]"];

export default MeasurementSleepSegmentTypesResult;

