/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MeasurementSleepSegmentType model module.
 * @module model/MeasurementSleepSegmentType
 * @version 1.0.0
 */
class MeasurementSleepSegmentType {
    /**
     * Constructs a new <code>MeasurementSleepSegmentType</code>.
     * Sleep segment type lookup record.
     * @alias module:model/MeasurementSleepSegmentType
     * @param id {String} 
     * @param sleepSegmentTypeId {String} 
     * @param description {String} 
     */
    constructor(id, sleepSegmentTypeId, description) { 
        
        MeasurementSleepSegmentType.initialize(this, id, sleepSegmentTypeId, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, sleepSegmentTypeId, description) { 
        obj['id'] = id;
        obj['sleep_segment_type_id'] = sleepSegmentTypeId;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>MeasurementSleepSegmentType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementSleepSegmentType} obj Optional instance to populate.
     * @return {module:model/MeasurementSleepSegmentType} The populated <code>MeasurementSleepSegmentType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MeasurementSleepSegmentType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('sleep_segment_type_id')) {
                obj['sleep_segment_type_id'] = ApiClient.convertToType(data['sleep_segment_type_id'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MeasurementSleepSegmentType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MeasurementSleepSegmentType</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MeasurementSleepSegmentType.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['sleep_segment_type_id'] && !(typeof data['sleep_segment_type_id'] === 'string' || data['sleep_segment_type_id'] instanceof String)) {
            throw new Error("Expected the field `sleep_segment_type_id` to be a primitive type in the JSON string but got " + data['sleep_segment_type_id']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

MeasurementSleepSegmentType.RequiredProperties = ["id", "sleep_segment_type_id", "description"];

/**
 * @member {String} id
 */
MeasurementSleepSegmentType.prototype['id'] = undefined;

/**
 * @member {String} sleep_segment_type_id
 */
MeasurementSleepSegmentType.prototype['sleep_segment_type_id'] = undefined;

/**
 * @member {String} description
 */
MeasurementSleepSegmentType.prototype['description'] = undefined;






export default MeasurementSleepSegmentType;

