/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MeasurementUnit model module.
 * @module model/MeasurementUnit
 * @version 1.0.0
 */
class MeasurementUnit {
    /**
     * Constructs a new <code>MeasurementUnit</code>.
     * Unit of measurement and its definition.
     * @alias module:model/MeasurementUnit
     * @param id {String} 
     * @param unit {String} 
     * @param definition {String} 
     */
    constructor(id, unit, definition) { 
        
        MeasurementUnit.initialize(this, id, unit, definition);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, unit, definition) { 
        obj['id'] = id;
        obj['unit'] = unit;
        obj['definition'] = definition;
    }

    /**
     * Constructs a <code>MeasurementUnit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementUnit} obj Optional instance to populate.
     * @return {module:model/MeasurementUnit} The populated <code>MeasurementUnit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MeasurementUnit();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('definition')) {
                obj['definition'] = ApiClient.convertToType(data['definition'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MeasurementUnit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MeasurementUnit</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MeasurementUnit.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['unit'] && !(typeof data['unit'] === 'string' || data['unit'] instanceof String)) {
            throw new Error("Expected the field `unit` to be a primitive type in the JSON string but got " + data['unit']);
        }
        // ensure the json data is a string
        if (data['definition'] && !(typeof data['definition'] === 'string' || data['definition'] instanceof String)) {
            throw new Error("Expected the field `definition` to be a primitive type in the JSON string but got " + data['definition']);
        }

        return true;
    }


}

MeasurementUnit.RequiredProperties = ["id", "unit", "definition"];

/**
 * @member {String} id
 */
MeasurementUnit.prototype['id'] = undefined;

/**
 * @member {String} unit
 */
MeasurementUnit.prototype['unit'] = undefined;

/**
 * @member {String} definition
 */
MeasurementUnit.prototype['definition'] = undefined;






export default MeasurementUnit;

