/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementBodyPosition from './MeasurementBodyPosition';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementBodyPositionResult model module.
 * @module model/MeasurementBodyPositionResult
 * @version 1.0.0
 */
class MeasurementBodyPositionResult {
    /**
     * Constructs a new <code>MeasurementBodyPositionResult</code>.
     * Body position or an application-level error object.
     * @alias module:model/MeasurementBodyPositionResult
     * @param {(module:model/MeasurementBodyPosition|module:model/MeasurementsErrorResponse)} instance The actual instance to initialize MeasurementBodyPositionResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MeasurementBodyPosition) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementBodyPosition.validateJSON(instance); // throw an exception if no match
                // create MeasurementBodyPosition from JS object
                this.actualInstance = MeasurementBodyPosition.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementBodyPosition
            errorMessages.push("Failed to construct MeasurementBodyPosition: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementBodyPositionResult` with oneOf schemas MeasurementBodyPosition, MeasurementsErrorResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementBodyPositionResult` with oneOf schemas MeasurementBodyPosition, MeasurementsErrorResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementBodyPositionResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementBodyPositionResult} obj Optional instance to populate.
     * @return {module:model/MeasurementBodyPositionResult} The populated <code>MeasurementBodyPositionResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementBodyPositionResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementBodyPosition</code>, <code>MeasurementsErrorResponse</code>.
     * @return {(module:model/MeasurementBodyPosition|module:model/MeasurementsErrorResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementBodyPosition</code>, <code>MeasurementsErrorResponse</code>.
     * @param {(module:model/MeasurementBodyPosition|module:model/MeasurementsErrorResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementBodyPositionResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementBodyPositionResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementBodyPositionResult} An instance of MeasurementBodyPositionResult.
     */
    static fromJSON = function(json_string){
        return MeasurementBodyPositionResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} id
 */
MeasurementBodyPositionResult.prototype['id'] = undefined;

/**
 * @member {String} body_position_id
 */
MeasurementBodyPositionResult.prototype['body_position_id'] = undefined;

/**
 * @member {String} description
 */
MeasurementBodyPositionResult.prototype['description'] = undefined;

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementBodyPositionResult.prototype['error'] = undefined;


MeasurementBodyPositionResult.OneOf = ["MeasurementBodyPosition", "MeasurementsErrorResponse"];

export default MeasurementBodyPositionResult;

