/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementBodyTemperatureLocation from './MeasurementBodyTemperatureLocation';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementBodyTemperatureLocationsResult model module.
 * @module model/MeasurementBodyTemperatureLocationsResult
 * @version 1.0.0
 */
class MeasurementBodyTemperatureLocationsResult {
    /**
     * Constructs a new <code>MeasurementBodyTemperatureLocationsResult</code>.
     * Available body temperature locations or an application-level error object.
     * @alias module:model/MeasurementBodyTemperatureLocationsResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementBodyTemperatureLocation])} instance The actual instance to initialize MeasurementBodyTemperatureLocationsResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available body temperature locations.
        try {
            if (instance instanceof [MeasurementBodyTemperatureLocation]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementBodyTemperatureLocation].validateJSON(instance); // throw an exception if no match
                // create [MeasurementBodyTemperatureLocation] from JS object
                this.actualInstance = [MeasurementBodyTemperatureLocation].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementBodyTemperatureLocation]
            errorMessages.push("Failed to construct [MeasurementBodyTemperatureLocation]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementBodyTemperatureLocationsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementBodyTemperatureLocation]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementBodyTemperatureLocationsResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementBodyTemperatureLocation]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementBodyTemperatureLocationsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementBodyTemperatureLocationsResult} obj Optional instance to populate.
     * @return {module:model/MeasurementBodyTemperatureLocationsResult} The populated <code>MeasurementBodyTemperatureLocationsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementBodyTemperatureLocationsResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementBodyTemperatureLocation]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementBodyTemperatureLocation])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementBodyTemperatureLocation]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementBodyTemperatureLocation])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementBodyTemperatureLocationsResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementBodyTemperatureLocationsResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementBodyTemperatureLocationsResult} An instance of MeasurementBodyTemperatureLocationsResult.
     */
    static fromJSON = function(json_string){
        return MeasurementBodyTemperatureLocationsResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementBodyTemperatureLocationsResult.prototype['error'] = undefined;


MeasurementBodyTemperatureLocationsResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementBodyTemperatureLocation]"];

export default MeasurementBodyTemperatureLocationsResult;

