/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementCervicalMucusAmount from './MeasurementCervicalMucusAmount';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementCervicalMucusAmountResult model module.
 * @module model/MeasurementCervicalMucusAmountResult
 * @version 1.0.0
 */
class MeasurementCervicalMucusAmountResult {
    /**
     * Constructs a new <code>MeasurementCervicalMucusAmountResult</code>.
     * Cervical mucus amount or an application-level error object.
     * @alias module:model/MeasurementCervicalMucusAmountResult
     * @param {(module:model/MeasurementCervicalMucusAmount|module:model/MeasurementsErrorResponse)} instance The actual instance to initialize MeasurementCervicalMucusAmountResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MeasurementCervicalMucusAmount) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementCervicalMucusAmount.validateJSON(instance); // throw an exception if no match
                // create MeasurementCervicalMucusAmount from JS object
                this.actualInstance = MeasurementCervicalMucusAmount.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementCervicalMucusAmount
            errorMessages.push("Failed to construct MeasurementCervicalMucusAmount: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementCervicalMucusAmountResult` with oneOf schemas MeasurementCervicalMucusAmount, MeasurementsErrorResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementCervicalMucusAmountResult` with oneOf schemas MeasurementCervicalMucusAmount, MeasurementsErrorResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementCervicalMucusAmountResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementCervicalMucusAmountResult} obj Optional instance to populate.
     * @return {module:model/MeasurementCervicalMucusAmountResult} The populated <code>MeasurementCervicalMucusAmountResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementCervicalMucusAmountResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementCervicalMucusAmount</code>, <code>MeasurementsErrorResponse</code>.
     * @return {(module:model/MeasurementCervicalMucusAmount|module:model/MeasurementsErrorResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementCervicalMucusAmount</code>, <code>MeasurementsErrorResponse</code>.
     * @param {(module:model/MeasurementCervicalMucusAmount|module:model/MeasurementsErrorResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementCervicalMucusAmountResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementCervicalMucusAmountResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementCervicalMucusAmountResult} An instance of MeasurementCervicalMucusAmountResult.
     */
    static fromJSON = function(json_string){
        return MeasurementCervicalMucusAmountResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} id
 */
MeasurementCervicalMucusAmountResult.prototype['id'] = undefined;

/**
 * @member {String} cervical_mucus_amount_id
 */
MeasurementCervicalMucusAmountResult.prototype['cervical_mucus_amount_id'] = undefined;

/**
 * @member {String} description
 */
MeasurementCervicalMucusAmountResult.prototype['description'] = undefined;

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementCervicalMucusAmountResult.prototype['error'] = undefined;


MeasurementCervicalMucusAmountResult.OneOf = ["MeasurementCervicalMucusAmount", "MeasurementsErrorResponse"];

export default MeasurementCervicalMucusAmountResult;

