/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MeasurementExerciseType from './MeasurementExerciseType';
import MeasurementsErrorDetails from './MeasurementsErrorDetails';
import MeasurementsErrorResponse from './MeasurementsErrorResponse';

/**
 * The MeasurementExerciseTypesResult model module.
 * @module model/MeasurementExerciseTypesResult
 * @version 1.0.0
 */
class MeasurementExerciseTypesResult {
    /**
     * Constructs a new <code>MeasurementExerciseTypesResult</code>.
     * Available exercise types or an application-level error object.
     * @alias module:model/MeasurementExerciseTypesResult
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementExerciseType])} instance The actual instance to initialize MeasurementExerciseTypesResult.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        // Available exercise types.
        try {
            if (instance instanceof [MeasurementExerciseType]) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                [MeasurementExerciseType].validateJSON(instance); // throw an exception if no match
                // create [MeasurementExerciseType] from JS object
                this.actualInstance = [MeasurementExerciseType].constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into [MeasurementExerciseType]
            errorMessages.push("Failed to construct [MeasurementExerciseType]: " + err)
        }

        try {
            if (instance instanceof MeasurementsErrorResponse) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MeasurementsErrorResponse.validateJSON(instance); // throw an exception if no match
                // create MeasurementsErrorResponse from JS object
                this.actualInstance = MeasurementsErrorResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MeasurementsErrorResponse
            errorMessages.push("Failed to construct MeasurementsErrorResponse: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MeasurementExerciseTypesResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementExerciseType]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MeasurementExerciseTypesResult` with oneOf schemas MeasurementsErrorResponse, [MeasurementExerciseType]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MeasurementExerciseTypesResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementExerciseTypesResult} obj Optional instance to populate.
     * @return {module:model/MeasurementExerciseTypesResult} The populated <code>MeasurementExerciseTypesResult</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MeasurementExerciseTypesResult(data);
    }

    /**
     * Gets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementExerciseType]</code>.
     * @return {(module:model/MeasurementsErrorResponse|module:model/[MeasurementExerciseType])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MeasurementsErrorResponse</code>, <code>[MeasurementExerciseType]</code>.
     * @param {(module:model/MeasurementsErrorResponse|module:model/[MeasurementExerciseType])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MeasurementExerciseTypesResult.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MeasurementExerciseTypesResult from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MeasurementExerciseTypesResult} An instance of MeasurementExerciseTypesResult.
     */
    static fromJSON = function(json_string){
        return MeasurementExerciseTypesResult.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/MeasurementsErrorDetails} error
 */
MeasurementExerciseTypesResult.prototype['error'] = undefined;


MeasurementExerciseTypesResult.OneOf = ["MeasurementsErrorResponse", "[MeasurementExerciseType]"];

export default MeasurementExerciseTypesResult;

