/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LivewellAboutAlternateName from './LivewellAboutAlternateName';
import MedicineAbout from './MedicineAbout';
import MedicineAuthor from './MedicineAuthor';
import MedicineBreadcrumb from './MedicineBreadcrumb';
import MedicineContentElement from './MedicineContentElement';
import MedicineCopyrightHolder from './MedicineCopyrightHolder';
import MedicineHealthTopicContent from './MedicineHealthTopicContent';
import MedicineRelatedLink from './MedicineRelatedLink';

/**
 * The MedicineData model module.
 * @module model/MedicineData
 * @version 1.0.0
 */
class MedicineData {
    /**
     * Constructs a new <code>MedicineData</code>.
     * Medicine information returned from the stored NHS Medicines dataset. The exact structure varies by requested route and query parameters.
     * @alias module:model/MedicineData
     */
    constructor() { 
        
        MedicineData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MedicineData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MedicineData} obj Optional instance to populate.
     * @return {module:model/MedicineData} The populated <code>MedicineData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MedicineData();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('copyrightHolder')) {
                obj['copyrightHolder'] = MedicineCopyrightHolder.constructFromObject(data['copyrightHolder']);
            }
            if (data.hasOwnProperty('license')) {
                obj['license'] = ApiClient.convertToType(data['license'], 'String');
            }
            if (data.hasOwnProperty('author')) {
                obj['author'] = MedicineAuthor.constructFromObject(data['author']);
            }
            if (data.hasOwnProperty('about')) {
                obj['about'] = MedicineAbout.constructFromObject(data['about']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], ['String']);
            }
            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = LivewellAboutAlternateName.constructFromObject(data['keywords']);
            }
            if (data.hasOwnProperty('dateModified')) {
                obj['dateModified'] = ApiClient.convertToType(data['dateModified'], 'Date');
            }
            if (data.hasOwnProperty('lastReviewed')) {
                obj['lastReviewed'] = ApiClient.convertToType(data['lastReviewed'], ['String']);
            }
            if (data.hasOwnProperty('hasPart')) {
                obj['hasPart'] = ApiClient.convertToType(data['hasPart'], [MedicineHealthTopicContent]);
            }
            if (data.hasOwnProperty('breadcrumb')) {
                obj['breadcrumb'] = MedicineBreadcrumb.constructFromObject(data['breadcrumb']);
            }
            if (data.hasOwnProperty('relatedLink')) {
                obj['relatedLink'] = ApiClient.convertToType(data['relatedLink'], [MedicineRelatedLink]);
            }
            if (data.hasOwnProperty('headline')) {
                obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
            }
            if (data.hasOwnProperty('contentSubTypes')) {
                obj['contentSubTypes'] = ApiClient.convertToType(data['contentSubTypes'], ['String']);
            }
            if (data.hasOwnProperty('mainEntityOfPage')) {
                obj['mainEntityOfPage'] = ApiClient.convertToType(data['mainEntityOfPage'], [MedicineContentElement]);
            }
            if (data.hasOwnProperty('webpage')) {
                obj['webpage'] = ApiClient.convertToType(data['webpage'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('route_mapping')) {
                obj['route_mapping'] = ApiClient.convertToType(data['route_mapping'], 'String');
            }
            if (data.hasOwnProperty('redirect')) {
                obj['redirect'] = ApiClient.convertToType(data['redirect'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MedicineData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MedicineData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@context'] && !(typeof data['@context'] === 'string' || data['@context'] instanceof String)) {
            throw new Error("Expected the field `@context` to be a primitive type in the JSON string but got " + data['@context']);
        }
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `copyrightHolder`
        if (data['copyrightHolder']) { // data not null
          MedicineCopyrightHolder.validateJSON(data['copyrightHolder']);
        }
        // ensure the json data is a string
        if (data['license'] && !(typeof data['license'] === 'string' || data['license'] instanceof String)) {
            throw new Error("Expected the field `license` to be a primitive type in the JSON string but got " + data['license']);
        }
        // validate the optional field `author`
        if (data['author']) { // data not null
          MedicineAuthor.validateJSON(data['author']);
        }
        // validate the optional field `about`
        if (data['about']) { // data not null
          MedicineAbout.validateJSON(data['about']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['genre'])) {
            throw new Error("Expected the field `genre` to be an array in the JSON data but got " + data['genre']);
        }
        // validate the optional field `keywords`
        if (data['keywords']) { // data not null
          LivewellAboutAlternateName.validateJSON(data['keywords']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lastReviewed'])) {
            throw new Error("Expected the field `lastReviewed` to be an array in the JSON data but got " + data['lastReviewed']);
        }
        if (data['hasPart']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['hasPart'])) {
                throw new Error("Expected the field `hasPart` to be an array in the JSON data but got " + data['hasPart']);
            }
            // validate the optional field `hasPart` (array)
            for (const item of data['hasPart']) {
                MedicineHealthTopicContent.validateJSON(item);
            };
        }
        // validate the optional field `breadcrumb`
        if (data['breadcrumb']) { // data not null
          MedicineBreadcrumb.validateJSON(data['breadcrumb']);
        }
        if (data['relatedLink']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['relatedLink'])) {
                throw new Error("Expected the field `relatedLink` to be an array in the JSON data but got " + data['relatedLink']);
            }
            // validate the optional field `relatedLink` (array)
            for (const item of data['relatedLink']) {
                MedicineRelatedLink.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['headline'] && !(typeof data['headline'] === 'string' || data['headline'] instanceof String)) {
            throw new Error("Expected the field `headline` to be a primitive type in the JSON string but got " + data['headline']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['contentSubTypes'])) {
            throw new Error("Expected the field `contentSubTypes` to be an array in the JSON data but got " + data['contentSubTypes']);
        }
        if (data['mainEntityOfPage']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['mainEntityOfPage'])) {
                throw new Error("Expected the field `mainEntityOfPage` to be an array in the JSON data but got " + data['mainEntityOfPage']);
            }
            // validate the optional field `mainEntityOfPage` (array)
            for (const item of data['mainEntityOfPage']) {
                MedicineContentElement.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['webpage'] && !(typeof data['webpage'] === 'string' || data['webpage'] instanceof String)) {
            throw new Error("Expected the field `webpage` to be a primitive type in the JSON string but got " + data['webpage']);
        }
        // ensure the json data is a string
        if (data['route_mapping'] && !(typeof data['route_mapping'] === 'string' || data['route_mapping'] instanceof String)) {
            throw new Error("Expected the field `route_mapping` to be a primitive type in the JSON string but got " + data['route_mapping']);
        }
        // ensure the json data is a string
        if (data['redirect'] && !(typeof data['redirect'] === 'string' || data['redirect'] instanceof String)) {
            throw new Error("Expected the field `redirect` to be a primitive type in the JSON string but got " + data['redirect']);
        }

        return true;
    }


}



/**
 * @member {String} @context
 */
MedicineData.prototype['@context'] = undefined;

/**
 * @member {String} @type
 */
MedicineData.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
MedicineData.prototype['name'] = undefined;

/**
 * @member {module:model/MedicineCopyrightHolder} copyrightHolder
 */
MedicineData.prototype['copyrightHolder'] = undefined;

/**
 * @member {String} license
 */
MedicineData.prototype['license'] = undefined;

/**
 * @member {module:model/MedicineAuthor} author
 */
MedicineData.prototype['author'] = undefined;

/**
 * @member {module:model/MedicineAbout} about
 */
MedicineData.prototype['about'] = undefined;

/**
 * @member {String} description
 */
MedicineData.prototype['description'] = undefined;

/**
 * @member {String} url
 */
MedicineData.prototype['url'] = undefined;

/**
 * @member {Array.<String>} genre
 */
MedicineData.prototype['genre'] = undefined;

/**
 * @member {module:model/LivewellAboutAlternateName} keywords
 */
MedicineData.prototype['keywords'] = undefined;

/**
 * @member {Date} dateModified
 */
MedicineData.prototype['dateModified'] = undefined;

/**
 * @member {Array.<String>} lastReviewed
 */
MedicineData.prototype['lastReviewed'] = undefined;

/**
 * @member {Array.<module:model/MedicineHealthTopicContent>} hasPart
 */
MedicineData.prototype['hasPart'] = undefined;

/**
 * @member {module:model/MedicineBreadcrumb} breadcrumb
 */
MedicineData.prototype['breadcrumb'] = undefined;

/**
 * @member {Array.<module:model/MedicineRelatedLink>} relatedLink
 */
MedicineData.prototype['relatedLink'] = undefined;

/**
 * @member {String} headline
 */
MedicineData.prototype['headline'] = undefined;

/**
 * @member {Array.<String>} contentSubTypes
 */
MedicineData.prototype['contentSubTypes'] = undefined;

/**
 * @member {Array.<module:model/MedicineContentElement>} mainEntityOfPage
 */
MedicineData.prototype['mainEntityOfPage'] = undefined;

/**
 * @member {String} webpage
 */
MedicineData.prototype['webpage'] = undefined;

/**
 * @member {Number} id
 */
MedicineData.prototype['id'] = undefined;

/**
 * @member {String} route_mapping
 */
MedicineData.prototype['route_mapping'] = undefined;

/**
 * @member {String} redirect
 */
MedicineData.prototype['redirect'] = undefined;






export default MedicineData;

