/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MedicineAnswerLinksInner from './MedicineAnswerLinksInner';

/**
 * The MedicineNestedEntity model module.
 * @module model/MedicineNestedEntity
 * @version 1.0.0
 */
class MedicineNestedEntity {
    /**
     * Constructs a new <code>MedicineNestedEntity</code>.
     * Flexible nested entity that may occur inside a content element&#39;s mainEntity property.
     * @alias module:model/MedicineNestedEntity
     * @extends Object
     */
    constructor() { 
        
        MedicineNestedEntity.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MedicineNestedEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MedicineNestedEntity} obj Optional instance to populate.
     * @return {module:model/MedicineNestedEntity} The populated <code>MedicineNestedEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MedicineNestedEntity();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('mainEntity')) {
                obj['mainEntity'] = ApiClient.convertToType(data['mainEntity'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [MedicineAnswerLinksInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MedicineNestedEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MedicineNestedEntity</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['mainEntity'] && !(typeof data['mainEntity'] === 'string' || data['mainEntity'] instanceof String)) {
            throw new Error("Expected the field `mainEntity` to be a primitive type in the JSON string but got " + data['mainEntity']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                MedicineAnswerLinksInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} mainEntity
 */
MedicineNestedEntity.prototype['mainEntity'] = undefined;

/**
 * @member {String} text
 */
MedicineNestedEntity.prototype['text'] = undefined;

/**
 * @member {Array.<module:model/MedicineAnswerLinksInner>} links
 */
MedicineNestedEntity.prototype['links'] = undefined;






export default MedicineNestedEntity;

