/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MedicinesNotFoundResponse model module.
 * @module model/MedicinesNotFoundResponse
 * @version 1.0.0
 */
class MedicinesNotFoundResponse {
    /**
     * Constructs a new <code>MedicinesNotFoundResponse</code>.
     * Application-level response returned with HTTP 200 when the requested Medicines route does not exist.
     * @alias module:model/MedicinesNotFoundResponse
     * @param message {module:model/MedicinesNotFoundResponse.MessageEnum} 
     * @param indexOfMedicinesRoutes {String} 
     */
    constructor(message, indexOfMedicinesRoutes) { 
        
        MedicinesNotFoundResponse.initialize(this, message, indexOfMedicinesRoutes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, indexOfMedicinesRoutes) { 
        obj['message'] = message;
        obj['index of Medicines routes'] = indexOfMedicinesRoutes;
    }

    /**
     * Constructs a <code>MedicinesNotFoundResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MedicinesNotFoundResponse} obj Optional instance to populate.
     * @return {module:model/MedicinesNotFoundResponse} The populated <code>MedicinesNotFoundResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MedicinesNotFoundResponse();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('index of Medicines routes')) {
                obj['index of Medicines routes'] = ApiClient.convertToType(data['index of Medicines routes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MedicinesNotFoundResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MedicinesNotFoundResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MedicinesNotFoundResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['index of Medicines routes'] && !(typeof data['index of Medicines routes'] === 'string' || data['index of Medicines routes'] instanceof String)) {
            throw new Error("Expected the field `index of Medicines routes` to be a primitive type in the JSON string but got " + data['index of Medicines routes']);
        }

        return true;
    }


}

MedicinesNotFoundResponse.RequiredProperties = ["message", "index of Medicines routes"];

/**
 * @member {module:model/MedicinesNotFoundResponse.MessageEnum} message
 */
MedicinesNotFoundResponse.prototype['message'] = undefined;

/**
 * @member {String} index of Medicines routes
 */
MedicinesNotFoundResponse.prototype['index of Medicines routes'] = undefined;





/**
 * Allowed values for the <code>message</code> property.
 * @enum {String}
 * @readonly
 */
MedicinesNotFoundResponse['MessageEnum'] = {

    /**
     * value: "the requested data does not exist"
     * @const
     */
    "the requested data does not exist": "the requested data does not exist",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default MedicinesNotFoundResponse;

