/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MentalHealthSearchFilter model module.
 * @module model/MentalHealthSearchFilter
 * @version 1.0.0
 */
class MentalHealthSearchFilter {
    /**
     * Constructs a new <code>MentalHealthSearchFilter</code>.
     * A structured filter used by the Mental Health search endpoint. Every filter must contain exactly value, operator and condition.
     * @alias module:model/MentalHealthSearchFilter
     * @param value {String} Text to search for. The value must not be empty and may contain only letters, numbers and whitespace.
     * @param operator {module:model/MentalHealthSearchFilter.OperatorEnum} Comparison operator accepted by the Mental Health search validator.
     * @param condition {module:model/MentalHealthSearchFilter.ConditionEnum} Logical condition accepted by the shared search validator. The property is required but may be empty. The Mental Health search implementation currently combines generated search clauses using AND.
     */
    constructor(value, operator, condition) { 
        
        MentalHealthSearchFilter.initialize(this, value, operator, condition);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value, operator, condition) { 
        obj['value'] = value;
        obj['operator'] = operator;
        obj['condition'] = condition;
    }

    /**
     * Constructs a <code>MentalHealthSearchFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MentalHealthSearchFilter} obj Optional instance to populate.
     * @return {module:model/MentalHealthSearchFilter} The populated <code>MentalHealthSearchFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MentalHealthSearchFilter();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('condition')) {
                obj['condition'] = ApiClient.convertToType(data['condition'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MentalHealthSearchFilter</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MentalHealthSearchFilter</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MentalHealthSearchFilter.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['operator'] && !(typeof data['operator'] === 'string' || data['operator'] instanceof String)) {
            throw new Error("Expected the field `operator` to be a primitive type in the JSON string but got " + data['operator']);
        }
        // ensure the json data is a string
        if (data['condition'] && !(typeof data['condition'] === 'string' || data['condition'] instanceof String)) {
            throw new Error("Expected the field `condition` to be a primitive type in the JSON string but got " + data['condition']);
        }

        return true;
    }


}

MentalHealthSearchFilter.RequiredProperties = ["value", "operator", "condition"];

/**
 * Text to search for. The value must not be empty and may contain only letters, numbers and whitespace.
 * @member {String} value
 */
MentalHealthSearchFilter.prototype['value'] = undefined;

/**
 * Comparison operator accepted by the Mental Health search validator.
 * @member {module:model/MentalHealthSearchFilter.OperatorEnum} operator
 */
MentalHealthSearchFilter.prototype['operator'] = undefined;

/**
 * Logical condition accepted by the shared search validator. The property is required but may be empty. The Mental Health search implementation currently combines generated search clauses using AND.
 * @member {module:model/MentalHealthSearchFilter.ConditionEnum} condition
 */
MentalHealthSearchFilter.prototype['condition'] = undefined;





/**
 * Allowed values for the <code>operator</code> property.
 * @enum {String}
 * @readonly
 */
MentalHealthSearchFilter['OperatorEnum'] = {

    /**
     * value: "LIKE"
     * @const
     */
    "LIKE": "LIKE",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};


/**
 * Allowed values for the <code>condition</code> property.
 * @enum {String}
 * @readonly
 */
MentalHealthSearchFilter['ConditionEnum'] = {

    /**
     * value: ""
     * @const
     */
    "empty": "",

    /**
     * value: "AND"
     * @const
     */
    "AND": "AND",

    /**
     * value: "OR"
     * @const
     */
    "OR": "OR",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default MentalHealthSearchFilter;

