/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MentalHealthBreadcrumbListItem from './MentalHealthBreadcrumbListItem';

/**
 * The MentalHealthBreadcrumb model module.
 * @module model/MentalHealthBreadcrumb
 * @version 1.0.0
 */
class MentalHealthBreadcrumb {
    /**
     * Constructs a new <code>MentalHealthBreadcrumb</code>.
     * @alias module:model/MentalHealthBreadcrumb
     */
    constructor() { 
        
        MentalHealthBreadcrumb.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MentalHealthBreadcrumb</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MentalHealthBreadcrumb} obj Optional instance to populate.
     * @return {module:model/MentalHealthBreadcrumb} The populated <code>MentalHealthBreadcrumb</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MentalHealthBreadcrumb();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('itemListElement')) {
                obj['itemListElement'] = ApiClient.convertToType(data['itemListElement'], [MentalHealthBreadcrumbListItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MentalHealthBreadcrumb</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MentalHealthBreadcrumb</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@context'] && !(typeof data['@context'] === 'string' || data['@context'] instanceof String)) {
            throw new Error("Expected the field `@context` to be a primitive type in the JSON string but got " + data['@context']);
        }
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        if (data['itemListElement']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['itemListElement'])) {
                throw new Error("Expected the field `itemListElement` to be an array in the JSON data but got " + data['itemListElement']);
            }
            // validate the optional field `itemListElement` (array)
            for (const item of data['itemListElement']) {
                MentalHealthBreadcrumbListItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} @context
 */
MentalHealthBreadcrumb.prototype['@context'] = undefined;

/**
 * @member {String} @type
 */
MentalHealthBreadcrumb.prototype['@type'] = undefined;

/**
 * @member {Array.<module:model/MentalHealthBreadcrumbListItem>} itemListElement
 */
MentalHealthBreadcrumb.prototype['itemListElement'] = undefined;






export default MentalHealthBreadcrumb;

