/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MentalHealthLinkObject from './MentalHealthLinkObject';

/**
 * The MentalHealthAnswerLinksInner model module.
 * @module model/MentalHealthAnswerLinksInner
 * @version 1.0.0
 */
class MentalHealthAnswerLinksInner {
    /**
     * Constructs a new <code>MentalHealthAnswerLinksInner</code>.
     * @alias module:model/MentalHealthAnswerLinksInner
     * @param {(module:model/MentalHealthLinkObject|module:model/String)} instance The actual instance to initialize MentalHealthAnswerLinksInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof MentalHealthLinkObject) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MentalHealthLinkObject.validateJSON(instance); // throw an exception if no match
                // create MentalHealthLinkObject from JS object
                this.actualInstance = MentalHealthLinkObject.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MentalHealthLinkObject
            errorMessages.push("Failed to construct MentalHealthLinkObject: " + err)
        }

        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `MentalHealthAnswerLinksInner` with oneOf schemas MentalHealthLinkObject, String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `MentalHealthAnswerLinksInner` with oneOf schemas MentalHealthLinkObject, String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>MentalHealthAnswerLinksInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MentalHealthAnswerLinksInner} obj Optional instance to populate.
     * @return {module:model/MentalHealthAnswerLinksInner} The populated <code>MentalHealthAnswerLinksInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new MentalHealthAnswerLinksInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>MentalHealthLinkObject</code>, <code>String</code>.
     * @return {(module:model/MentalHealthLinkObject|module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MentalHealthLinkObject</code>, <code>String</code>.
     * @param {(module:model/MentalHealthLinkObject|module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = MentalHealthAnswerLinksInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of MentalHealthAnswerLinksInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/MentalHealthAnswerLinksInner} An instance of MentalHealthAnswerLinksInner.
     */
    static fromJSON = function(json_string){
        return MentalHealthAnswerLinksInner.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * Placeholder key used within the original HTML. This may be omitted when no_html is enabled.
 * @member {String} key
 */
MentalHealthAnswerLinksInner.prototype['key'] = undefined;

/**
 * Equivalent route in the MRD API.
 * @member {String} mrd_api_link
 */
MentalHealthAnswerLinksInner.prototype['mrd_api_link'] = undefined;

/**
 * External web, NHS website or telephone link extracted from content.
 * @member {String} link
 */
MentalHealthAnswerLinksInner.prototype['link'] = undefined;


MentalHealthAnswerLinksInner.OneOf = ["MentalHealthLinkObject", "String"];

export default MentalHealthAnswerLinksInner;

