/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MentalHealthCopyrightHolder model module.
 * @module model/MentalHealthCopyrightHolder
 * @version 1.0.0
 */
class MentalHealthCopyrightHolder {
    /**
     * Constructs a new <code>MentalHealthCopyrightHolder</code>.
     * @alias module:model/MentalHealthCopyrightHolder
     */
    constructor() { 
        
        MentalHealthCopyrightHolder.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MentalHealthCopyrightHolder</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MentalHealthCopyrightHolder} obj Optional instance to populate.
     * @return {module:model/MentalHealthCopyrightHolder} The populated <code>MentalHealthCopyrightHolder</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MentalHealthCopyrightHolder();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MentalHealthCopyrightHolder</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MentalHealthCopyrightHolder</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
MentalHealthCopyrightHolder.prototype['name'] = undefined;

/**
 * @member {String} @type
 */
MentalHealthCopyrightHolder.prototype['@type'] = undefined;






export default MentalHealthCopyrightHolder;

