/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MentalHealthBreadcrumbItemData model module.
 * @module model/MentalHealthBreadcrumbItemData
 * @version 1.0.0
 */
class MentalHealthBreadcrumbItemData {
    /**
     * Constructs a new <code>MentalHealthBreadcrumbItemData</code>.
     * @alias module:model/MentalHealthBreadcrumbItemData
     */
    constructor() { 
        
        MentalHealthBreadcrumbItemData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MentalHealthBreadcrumbItemData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MentalHealthBreadcrumbItemData} obj Optional instance to populate.
     * @return {module:model/MentalHealthBreadcrumbItemData} The populated <code>MentalHealthBreadcrumbItemData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MentalHealthBreadcrumbItemData();

            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MentalHealthBreadcrumbItemData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MentalHealthBreadcrumbItemData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@id'] && !(typeof data['@id'] === 'string' || data['@id'] instanceof String)) {
            throw new Error("Expected the field `@id` to be a primitive type in the JSON string but got " + data['@id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['genre'])) {
            throw new Error("Expected the field `genre` to be an array in the JSON data but got " + data['genre']);
        }

        return true;
    }


}



/**
 * @member {String} @id
 */
MentalHealthBreadcrumbItemData.prototype['@id'] = undefined;

/**
 * @member {String} name
 */
MentalHealthBreadcrumbItemData.prototype['name'] = undefined;

/**
 * @member {Array.<String>} genre
 */
MentalHealthBreadcrumbItemData.prototype['genre'] = undefined;






export default MentalHealthBreadcrumbItemData;

