/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PregnancyBreadcrumbItemData from './PregnancyBreadcrumbItemData';

/**
 * The PregnancyBreadcrumbListItem model module.
 * @module model/PregnancyBreadcrumbListItem
 * @version 1.0.0
 */
class PregnancyBreadcrumbListItem {
    /**
     * Constructs a new <code>PregnancyBreadcrumbListItem</code>.
     * @alias module:model/PregnancyBreadcrumbListItem
     */
    constructor() { 
        
        PregnancyBreadcrumbListItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PregnancyBreadcrumbListItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PregnancyBreadcrumbListItem} obj Optional instance to populate.
     * @return {module:model/PregnancyBreadcrumbListItem} The populated <code>PregnancyBreadcrumbListItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PregnancyBreadcrumbListItem();

            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = PregnancyBreadcrumbItemData.constructFromObject(data['item']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PregnancyBreadcrumbListItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PregnancyBreadcrumbListItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // validate the optional field `item`
        if (data['item']) { // data not null
          PregnancyBreadcrumbItemData.validateJSON(data['item']);
        }

        return true;
    }


}



/**
 * @member {String} @type
 */
PregnancyBreadcrumbListItem.prototype['@type'] = undefined;

/**
 * @member {Number} position
 */
PregnancyBreadcrumbListItem.prototype['position'] = undefined;

/**
 * @member {module:model/PregnancyBreadcrumbItemData} item
 */
PregnancyBreadcrumbListItem.prototype['item'] = undefined;






export default PregnancyBreadcrumbListItem;

