/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PregnancyContentElement from './PregnancyContentElement';

/**
 * The PregnancyHealthTopicContent model module.
 * @module model/PregnancyHealthTopicContent
 * @version 1.0.0
 */
class PregnancyHealthTopicContent {
    /**
     * Constructs a new <code>PregnancyHealthTopicContent</code>.
     * A structured health-topic section included within a Pregnancy page.
     * @alias module:model/PregnancyHealthTopicContent
     * @extends Object
     */
    constructor() { 
        
        PregnancyHealthTopicContent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PregnancyHealthTopicContent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PregnancyHealthTopicContent} obj Optional instance to populate.
     * @return {module:model/PregnancyHealthTopicContent} The populated <code>PregnancyHealthTopicContent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PregnancyHealthTopicContent();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('hasHealthAspect')) {
                obj['hasHealthAspect'] = ApiClient.convertToType(data['hasHealthAspect'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('headline')) {
                obj['headline'] = ApiClient.convertToType(data['headline'], 'String');
            }
            if (data.hasOwnProperty('hasPart')) {
                obj['hasPart'] = ApiClient.convertToType(data['hasPart'], [PregnancyContentElement]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PregnancyHealthTopicContent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PregnancyHealthTopicContent</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['hasHealthAspect'] && !(typeof data['hasHealthAspect'] === 'string' || data['hasHealthAspect'] instanceof String)) {
            throw new Error("Expected the field `hasHealthAspect` to be a primitive type in the JSON string but got " + data['hasHealthAspect']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['headline'] && !(typeof data['headline'] === 'string' || data['headline'] instanceof String)) {
            throw new Error("Expected the field `headline` to be a primitive type in the JSON string but got " + data['headline']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['hasPart'])) {
            throw new Error("Expected the field `hasPart` to be an array in the JSON data but got " + data['hasPart']);
        }

        return true;
    }


}



/**
 * @member {String} @type
 */
PregnancyHealthTopicContent.prototype['@type'] = undefined;

/**
 * Schema.org health aspect represented by the section.
 * @member {String} hasHealthAspect
 */
PregnancyHealthTopicContent.prototype['hasHealthAspect'] = undefined;

/**
 * Section URL. By default this is normally an MRD API URL and is rewritten where eligible when nhs_links is enabled.
 * @member {String} url
 */
PregnancyHealthTopicContent.prototype['url'] = undefined;

/**
 * @member {String} description
 */
PregnancyHealthTopicContent.prototype['description'] = undefined;

/**
 * Section heading. Empty strings are valid.
 * @member {String} headline
 */
PregnancyHealthTopicContent.prototype['headline'] = undefined;

/**
 * @member {Array.<module:model/PregnancyContentElement>} hasPart
 */
PregnancyHealthTopicContent.prototype['hasPart'] = undefined;






export default PregnancyHealthTopicContent;

