/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PregnancyErrorResponse model module.
 * @module model/PregnancyErrorResponse
 * @version 1.0.0
 */
class PregnancyErrorResponse {
    /**
     * Constructs a new <code>PregnancyErrorResponse</code>.
     * Error returned when a Pregnancy request cannot be processed.
     * @alias module:model/PregnancyErrorResponse
     * @param success {module:model/PregnancyErrorResponse.SuccessEnum} 
     * @param message {String} 
     */
    constructor(success, message) { 
        
        PregnancyErrorResponse.initialize(this, success, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, success, message) { 
        obj['success'] = success;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>PregnancyErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PregnancyErrorResponse} obj Optional instance to populate.
     * @return {module:model/PregnancyErrorResponse} The populated <code>PregnancyErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PregnancyErrorResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PregnancyErrorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PregnancyErrorResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PregnancyErrorResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

PregnancyErrorResponse.RequiredProperties = ["success", "message"];

/**
 * @member {module:model/PregnancyErrorResponse.SuccessEnum} success
 */
PregnancyErrorResponse.prototype['success'] = undefined;

/**
 * @member {String} message
 */
PregnancyErrorResponse.prototype['message'] = undefined;





/**
 * Allowed values for the <code>success</code> property.
 * @enum {Number}
 * @readonly
 */
PregnancyErrorResponse['SuccessEnum'] = {

    /**
     * value: 0
     * @const
     */
    "0": 0,

    /**
     * value: 11184809
     * @const
     */
    "unknown_default_open_api": 11184809
};



export default PregnancyErrorResponse;

