/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConditionVideoObjectIdentifier from './ConditionVideoObjectIdentifier';
import PregnancyAnswer from './PregnancyAnswer';
import PregnancyAnswerLinksInner from './PregnancyAnswerLinksInner';
import PregnancyContentElement from './PregnancyContentElement';
import PregnancyContentElementMainEntity from './PregnancyContentElementMainEntity';
import PregnancyVideoObject from './PregnancyVideoObject';

/**
 * The PregnancyContentElementMainEntityOfPageInner model module.
 * @module model/PregnancyContentElementMainEntityOfPageInner
 * @version 1.0.0
 */
class PregnancyContentElementMainEntityOfPageInner {
    /**
     * Constructs a new <code>PregnancyContentElementMainEntityOfPageInner</code>.
     * @alias module:model/PregnancyContentElementMainEntityOfPageInner
     * @param {(module:model/PregnancyContentElement|module:model/PregnancyVideoObject)} instance The actual instance to initialize PregnancyContentElementMainEntityOfPageInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof PregnancyContentElement) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PregnancyContentElement.validateJSON(instance); // throw an exception if no match
                // create PregnancyContentElement from JS object
                this.actualInstance = PregnancyContentElement.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PregnancyContentElement
            errorMessages.push("Failed to construct PregnancyContentElement: " + err)
        }

        try {
            if (instance instanceof PregnancyVideoObject) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PregnancyVideoObject.validateJSON(instance); // throw an exception if no match
                // create PregnancyVideoObject from JS object
                this.actualInstance = PregnancyVideoObject.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PregnancyVideoObject
            errorMessages.push("Failed to construct PregnancyVideoObject: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `PregnancyContentElementMainEntityOfPageInner` with oneOf schemas PregnancyContentElement, PregnancyVideoObject. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `PregnancyContentElementMainEntityOfPageInner` with oneOf schemas PregnancyContentElement, PregnancyVideoObject. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>PregnancyContentElementMainEntityOfPageInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PregnancyContentElementMainEntityOfPageInner} obj Optional instance to populate.
     * @return {module:model/PregnancyContentElementMainEntityOfPageInner} The populated <code>PregnancyContentElementMainEntityOfPageInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new PregnancyContentElementMainEntityOfPageInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>PregnancyContentElement</code>, <code>PregnancyVideoObject</code>.
     * @return {(module:model/PregnancyContentElement|module:model/PregnancyVideoObject)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>PregnancyContentElement</code>, <code>PregnancyVideoObject</code>.
     * @param {(module:model/PregnancyContentElement|module:model/PregnancyVideoObject)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = PregnancyContentElementMainEntityOfPageInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of PregnancyContentElementMainEntityOfPageInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/PregnancyContentElementMainEntityOfPageInner} An instance of PregnancyContentElementMainEntityOfPageInner.
     */
    static fromJSON = function(json_string){
        return PregnancyContentElementMainEntityOfPageInner.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} @type
 */
PregnancyContentElementMainEntityOfPageInner.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
PregnancyContentElementMainEntityOfPageInner.prototype['name'] = undefined;

/**
 * @member {module:model/ConditionVideoObjectIdentifier} identifier
 */
PregnancyContentElementMainEntityOfPageInner.prototype['identifier'] = undefined;

/**
 * @member {Number} position
 */
PregnancyContentElementMainEntityOfPageInner.prototype['position'] = undefined;

/**
 * Element heading. Empty strings are valid.
 * @member {String} headline
 */
PregnancyContentElementMainEntityOfPageInner.prototype['headline'] = undefined;

/**
 * @member {String} description
 */
PregnancyContentElementMainEntityOfPageInner.prototype['description'] = undefined;

/**
 * Element URL. MRD API URLs are normally returned by default and NHS URLs are returned when nhs_links is enabled.
 * @member {String} url
 */
PregnancyContentElementMainEntityOfPageInner.prototype['url'] = undefined;

/**
 * Element content. HTML is retained by default. When no_html is enabled, markup is removed and extracted links may be moved into links.
 * @member {String} text
 */
PregnancyContentElementMainEntityOfPageInner.prototype['text'] = undefined;

/**
 * Caption content when supplied by the source. This content is processed using the selected content formatter.
 * @member {String} caption
 */
PregnancyContentElementMainEntityOfPageInner.prototype['caption'] = undefined;

/**
 * Credit content when supplied by the source. This content is processed using the selected content formatter.
 * @member {String} credit
 */
PregnancyContentElementMainEntityOfPageInner.prototype['credit'] = undefined;

/**
 * Links extracted while formatting text, caption, credit or nested content.
 * @member {Array.<module:model/PregnancyAnswerLinksInner>} links
 */
PregnancyContentElementMainEntityOfPageInner.prototype['links'] = undefined;

/**
 * @member {module:model/PregnancyAnswer} acceptedAnswer
 */
PregnancyContentElementMainEntityOfPageInner.prototype['acceptedAnswer'] = undefined;

/**
 * @member {module:model/PregnancyContentElementMainEntity} mainEntity
 */
PregnancyContentElementMainEntityOfPageInner.prototype['mainEntity'] = undefined;

/**
 * Nested Pregnancy page content.
 * @member {Array.<module:model/PregnancyContentElementMainEntityOfPageInner>} mainEntityOfPage
 */
PregnancyContentElementMainEntityOfPageInner.prototype['mainEntityOfPage'] = undefined;

/**
 * Nested Pregnancy content.
 * @member {Array.<module:model/PregnancyContentElement>} hasPart
 */
PregnancyContentElementMainEntityOfPageInner.prototype['hasPart'] = undefined;

/**
 * @member {String} thumbnailUrl
 */
PregnancyContentElementMainEntityOfPageInner.prototype['thumbnailUrl'] = undefined;

/**
 * @member {String} uploadDate
 */
PregnancyContentElementMainEntityOfPageInner.prototype['uploadDate'] = undefined;

/**
 * @member {String} contentUrl
 */
PregnancyContentElementMainEntityOfPageInner.prototype['contentUrl'] = undefined;

/**
 * @member {String} embedUrl
 */
PregnancyContentElementMainEntityOfPageInner.prototype['embedUrl'] = undefined;


PregnancyContentElementMainEntityOfPageInner.OneOf = ["PregnancyContentElement", "PregnancyVideoObject"];

export default PregnancyContentElementMainEntityOfPageInner;

