/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PregnancyAnswerLinksInner from './PregnancyAnswerLinksInner';
import PregnancyContentElement from './PregnancyContentElement';

/**
 * The PregnancyAnswer model module.
 * @module model/PregnancyAnswer
 * @version 1.0.0
 */
class PregnancyAnswer {
    /**
     * Constructs a new <code>PregnancyAnswer</code>.
     * An answer returned within a question-style Pregnancy content block.
     * @alias module:model/PregnancyAnswer
     * @extends Object
     */
    constructor() { 
        
        PregnancyAnswer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PregnancyAnswer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PregnancyAnswer} obj Optional instance to populate.
     * @return {module:model/PregnancyAnswer} The populated <code>PregnancyAnswer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PregnancyAnswer();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [PregnancyAnswerLinksInner]);
            }
            if (data.hasOwnProperty('mainEntity')) {
                obj['mainEntity'] = ApiClient.convertToType(data['mainEntity'], [PregnancyContentElement]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PregnancyAnswer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PregnancyAnswer</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['@type'] && !(typeof data['@type'] === 'string' || data['@type'] instanceof String)) {
            throw new Error("Expected the field `@type` to be a primitive type in the JSON string but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                PregnancyAnswerLinksInner.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['mainEntity'])) {
            throw new Error("Expected the field `mainEntity` to be an array in the JSON data but got " + data['mainEntity']);
        }

        return true;
    }


}



/**
 * @member {String} @type
 */
PregnancyAnswer.prototype['@type'] = undefined;

/**
 * Answer text. HTML is retained by default and removed when no_html is enabled.
 * @member {String} text
 */
PregnancyAnswer.prototype['text'] = undefined;

/**
 * Links extracted while formatting the answer text.
 * @member {Array.<module:model/PregnancyAnswerLinksInner>} links
 */
PregnancyAnswer.prototype['links'] = undefined;

/**
 * Nested answer content when supplied by the source.
 * @member {Array.<module:model/PregnancyContentElement>} mainEntity
 */
PregnancyAnswer.prototype['mainEntity'] = undefined;






export default PregnancyAnswer;

