/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AlissNamedSlugItem from '../model/AlissNamedSlugItem';
import AlissService from '../model/AlissService';
import AlissServiceAreaReference from '../model/AlissServiceAreaReference';
import AlissServiceCount from '../model/AlissServiceCount';
import AuthErrorResponse from '../model/AuthErrorResponse';
import ErrorResponse from '../model/ErrorResponse';
import SearchAlissServicesFiltersParameter from '../model/SearchAlissServicesFiltersParameter';

/**
* ALISS service.
* @module api/ALISSApi
* @version 1.0.0
*/
export default class ALISSApi {

    /**
    * Constructs a new ALISSApi. 
    * @alias module:api/ALISSApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the countAlissServices operation.
     * @callback module:api/ALISSApi~countAlissServicesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlissServiceCount>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Count matching ALISS services
     * Returns the number of distinct ALISS services matching the supplied structured filters.
     * @param {module:model/String} xMrdScopes MRD service scope required for ALISS endpoints.
     * @param {Object} opts Optional parameters
     * @param {module:model/SearchAlissServicesFiltersParameter} [filters] Structured filters used to search ALISS services. Supported datasets are services, organisations, categories, service_areas, locations, accessibility_features and community_groups. Each filter requires field, value and operator. Every filter except the final filter must also contain condition.
     * @param {module:api/ALISSApi~countAlissServicesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlissServiceCount>}
     */
    countAlissServices(xMrdScopes, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling countAlissServices");
      }

      let pathParams = {
      };
      let queryParams = {
        'filters': opts['filters']
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlissServiceCount];
      return this.apiClient.callApi(
        '/aliss/get-services/search/count', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlissAccessibilityFeatures operation.
     * @callback module:api/ALISSApi~getAlissAccessibilityFeaturesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlissNamedSlugItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve ALISS accessibility features
     * @param {module:model/String} xMrdScopes MRD service scope required for ALISS endpoints.
     * @param {module:api/ALISSApi~getAlissAccessibilityFeaturesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlissNamedSlugItem>}
     */
    getAlissAccessibilityFeatures(xMrdScopes, callback) {
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getAlissAccessibilityFeatures");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlissNamedSlugItem];
      return this.apiClient.callApi(
        '/aliss/accessibility-features', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlissCategories operation.
     * @callback module:api/ALISSApi~getAlissCategoriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlissNamedSlugItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve ALISS categories
     * @param {module:model/String} xMrdScopes MRD service scope required for ALISS endpoints.
     * @param {module:api/ALISSApi~getAlissCategoriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlissNamedSlugItem>}
     */
    getAlissCategories(xMrdScopes, callback) {
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getAlissCategories");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlissNamedSlugItem];
      return this.apiClient.callApi(
        '/aliss/categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlissCommunityGroups operation.
     * @callback module:api/ALISSApi~getAlissCommunityGroupsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlissNamedSlugItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve ALISS community groups
     * @param {module:model/String} xMrdScopes MRD service scope required for ALISS endpoints.
     * @param {module:api/ALISSApi~getAlissCommunityGroupsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlissNamedSlugItem>}
     */
    getAlissCommunityGroups(xMrdScopes, callback) {
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getAlissCommunityGroups");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlissNamedSlugItem];
      return this.apiClient.callApi(
        '/aliss/community-groups', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlissOrganisations operation.
     * @callback module:api/ALISSApi~getAlissOrganisationsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlissNamedSlugItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve ALISS organisations
     * @param {module:model/String} xMrdScopes MRD service scope required for ALISS endpoints.
     * @param {module:api/ALISSApi~getAlissOrganisationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlissNamedSlugItem>}
     */
    getAlissOrganisations(xMrdScopes, callback) {
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getAlissOrganisations");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlissNamedSlugItem];
      return this.apiClient.callApi(
        '/aliss/organisations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlissServiceAreas operation.
     * @callback module:api/ALISSApi~getAlissServiceAreasCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlissServiceAreaReference>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve ALISS service areas
     * @param {module:model/String} xMrdScopes MRD service scope required for ALISS endpoints.
     * @param {module:api/ALISSApi~getAlissServiceAreasCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlissServiceAreaReference>}
     */
    getAlissServiceAreas(xMrdScopes, callback) {
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getAlissServiceAreas");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AlissServiceAreaReference];
      return this.apiClient.callApi(
        '/aliss/service-areas', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlissServicesByIds operation.
     * @callback module:api/ALISSApi~getAlissServicesByIdsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlissService>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve ALISS services by ID
     * Retrieves one or more services using a comma-separated list of service IDs.
     * @param {module:model/String} xMrdScopes MRD service scope required for ALISS endpoints.
     * @param {String} serviceIds One or more comma-separated ALISS service IDs.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [orderBy = 'services.id')] Field used to order matching services.
     * @param {module:model/String} [order = 'ASC')] Direction used to order matching services.
     * @param {Boolean} [geojson = false)] Controls whether GeoJSON is included with service-area data. The API accepts true or false case-insensitively.
     * @param {module:model/String} [format = 'JSON')] Response format.
     * @param {module:api/ALISSApi~getAlissServicesByIdsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlissService>}
     */
    getAlissServicesByIds(xMrdScopes, serviceIds, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getAlissServicesByIds");
      }
      // verify the required parameter 'serviceIds' is set
      if (serviceIds === undefined || serviceIds === null) {
        throw new Error("Missing the required parameter 'serviceIds' when calling getAlissServicesByIds");
      }

      let pathParams = {
        'service-ids': serviceIds
      };
      let queryParams = {
        'order_by': opts['orderBy'],
        'order': opts['order'],
        'geojson': opts['geojson'],
        'format': opts['format']
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/xml', 'application/json'];
      let returnType = [AlissService];
      return this.apiClient.callApi(
        '/aliss/get-services/{service-ids}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchAlissServices operation.
     * @callback module:api/ALISSApi~searchAlissServicesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AlissService>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search ALISS services
     * Searches ALISS services using structured filters, ordering and keyset pagination.
     * @param {module:model/String} xMrdScopes MRD service scope required for ALISS endpoints.
     * @param {Object} opts Optional parameters
     * @param {module:model/SearchAlissServicesFiltersParameter} [filters] Structured filters used to search ALISS services. Supported datasets are services, organisations, categories, service_areas, locations, accessibility_features and community_groups. Each filter requires field, value and operator. Every filter except the final filter must also contain condition.
     * @param {module:model/String} [orderBy = 'services.id')] Field used to order matching services.
     * @param {module:model/String} [order = 'ASC')] Direction used to order matching services.
     * @param {Number} [limit = 20)] Maximum number of services to return. The API defaults to 20 and rejects values greater than 100.
     * @param {String} [after] Keyset pagination value used to retrieve records after the supplied position. Only alphanumeric characters, commas, hyphens, underscores and spaces are accepted.
     * @param {String} [before] Keyset pagination value used to retrieve records before the supplied position. Only alphanumeric characters, commas, hyphens, underscores and spaces are accepted.
     * @param {Boolean} [geojson = false)] Controls whether GeoJSON is included with service-area data. The API accepts true or false case-insensitively.
     * @param {module:model/String} [format = 'JSON')] Response format.
     * @param {module:api/ALISSApi~searchAlissServicesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AlissService>}
     */
    searchAlissServices(xMrdScopes, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling searchAlissServices");
      }

      let pathParams = {
      };
      let queryParams = {
        'filters': opts['filters'],
        'order_by': opts['orderBy'],
        'order': opts['order'],
        'limit': opts['limit'],
        'after': opts['after'],
        'before': opts['before'],
        'geojson': opts['geojson'],
        'format': opts['format']
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/xml', 'application/json'];
      let returnType = [AlissService];
      return this.apiClient.callApi(
        '/aliss/get-services/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
