/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthErrorResponse from '../model/AuthErrorResponse';
import ConditionErrorResponse from '../model/ConditionErrorResponse';
import ConditionResponse from '../model/ConditionResponse';
import ConditionSearchFilter from '../model/ConditionSearchFilter';
import ConditionsRouteListResponse from '../model/ConditionsRouteListResponse';
import ConditionsSearchResponse from '../model/ConditionsSearchResponse';

/**
* Conditions service.
* @module api/ConditionsApi
* @version 1.0.0
*/
export default class ConditionsApi {

    /**
    * Constructs a new ConditionsApi. 
    * @alias module:api/ConditionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getConditionLevelOne operation.
     * @callback module:api/ConditionsApi~getConditionLevelOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConditionResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a first-level Conditions page
     * Returns a Conditions page identified by one route segment. The response may contain HTML by default. Use no_html to return processed plain text and nhs_links to return eligible original NHS URLs.
     * @param {module:model/String} xMrdScopes MRD service scope required for Conditions endpoints.
     * @param {String} param1 First Conditions route segment.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [noHtml] Removes HTML markup from returned content. When supplied, this parameter must be set to 'true'.
     * @param {module:model/String} [nhsLinks] Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to 'true'.
     * @param {module:api/ConditionsApi~getConditionLevelOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConditionResponse}
     */
    getConditionLevelOne(xMrdScopes, param1, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getConditionLevelOne");
      }
      // verify the required parameter 'param1' is set
      if (param1 === undefined || param1 === null) {
        throw new Error("Missing the required parameter 'param1' when calling getConditionLevelOne");
      }

      let pathParams = {
        'param1': param1
      };
      let queryParams = {
        'no_html': opts['noHtml'],
        'nhs_links': opts['nhsLinks']
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ConditionResponse;
      return this.apiClient.callApi(
        '/conditions/{param1}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getConditionLevelThree operation.
     * @callback module:api/ConditionsApi~getConditionLevelThreeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConditionResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a third-level Conditions page
     * Returns a Conditions page identified by three route segments. Responses may contain recursively nested web-page elements and video objects.
     * @param {module:model/String} xMrdScopes MRD service scope required for Conditions endpoints.
     * @param {String} param1 First Conditions route segment.
     * @param {String} param2 Second Conditions route segment.
     * @param {String} param3 Third Conditions route segment.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [noHtml] Removes HTML markup from returned content. When supplied, this parameter must be set to 'true'.
     * @param {module:model/String} [nhsLinks] Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to 'true'.
     * @param {module:api/ConditionsApi~getConditionLevelThreeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConditionResponse}
     */
    getConditionLevelThree(xMrdScopes, param1, param2, param3, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getConditionLevelThree");
      }
      // verify the required parameter 'param1' is set
      if (param1 === undefined || param1 === null) {
        throw new Error("Missing the required parameter 'param1' when calling getConditionLevelThree");
      }
      // verify the required parameter 'param2' is set
      if (param2 === undefined || param2 === null) {
        throw new Error("Missing the required parameter 'param2' when calling getConditionLevelThree");
      }
      // verify the required parameter 'param3' is set
      if (param3 === undefined || param3 === null) {
        throw new Error("Missing the required parameter 'param3' when calling getConditionLevelThree");
      }

      let pathParams = {
        'param1': param1,
        'param2': param2,
        'param3': param3
      };
      let queryParams = {
        'no_html': opts['noHtml'],
        'nhs_links': opts['nhsLinks']
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ConditionResponse;
      return this.apiClient.callApi(
        '/conditions/{param1}/{param2}/{param3}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getConditionLevelTwo operation.
     * @callback module:api/ConditionsApi~getConditionLevelTwoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConditionResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a second-level Conditions page
     * Returns a Conditions page identified by two route segments. The no_html and nhs_links parameters can be used separately or together.
     * @param {module:model/String} xMrdScopes MRD service scope required for Conditions endpoints.
     * @param {String} param1 First Conditions route segment.
     * @param {String} param2 Second Conditions route segment.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [noHtml] Removes HTML markup from returned content. When supplied, this parameter must be set to 'true'.
     * @param {module:model/String} [nhsLinks] Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to 'true'.
     * @param {module:api/ConditionsApi~getConditionLevelTwoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConditionResponse}
     */
    getConditionLevelTwo(xMrdScopes, param1, param2, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getConditionLevelTwo");
      }
      // verify the required parameter 'param1' is set
      if (param1 === undefined || param1 === null) {
        throw new Error("Missing the required parameter 'param1' when calling getConditionLevelTwo");
      }
      // verify the required parameter 'param2' is set
      if (param2 === undefined || param2 === null) {
        throw new Error("Missing the required parameter 'param2' when calling getConditionLevelTwo");
      }

      let pathParams = {
        'param1': param1,
        'param2': param2
      };
      let queryParams = {
        'no_html': opts['noHtml'],
        'nhs_links': opts['nhsLinks']
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ConditionResponse;
      return this.apiClient.callApi(
        '/conditions/{param1}/{param2}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getConditionRoutes operation.
     * @callback module:api/ConditionsApi~getConditionRoutesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConditionsRouteListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve available Conditions routes
     * Returns absolute URLs for the routes available in the NHS Conditions dataset.
     * @param {module:model/String} xMrdScopes MRD service scope required for Conditions endpoints.
     * @param {module:api/ConditionsApi~getConditionRoutesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConditionsRouteListResponse}
     */
    getConditionRoutes(xMrdScopes, callback) {
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling getConditionRoutes");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ConditionsRouteListResponse;
      return this.apiClient.callApi(
        '/conditions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchConditions operation.
     * @callback module:api/ConditionsApi~searchConditionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConditionsSearchResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search Conditions content
     * Searches the NHS Conditions dataset. By default the search is performed against page descriptions. When search_all is enabled, page text and expander content are also searched. The no_html option removes HTML from textual content and nhs_links changes eligible MRD URLs to original NHS URLs.
     * @param {module:model/String} xMrdScopes MRD service scope required for Conditions endpoints.
     * @param {Array.<module:model/ConditionSearchFilter>} filters Structured Conditions search filters supplied using indexed bracket notation, for example filters[0][operator]=LIKE&filters[0][value]=cancer&filters[0][condition]=AND&filters[1][operator]=LIKE&filters[1][value]=treatment&filters[1][condition]=. Each filter must contain exactly value, operator and condition.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [noHtml] Removes HTML markup from returned content. When supplied, this parameter must be set to 'true'.
     * @param {module:model/String} [nhsLinks] Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to 'true'.
     * @param {module:model/String} [searchAll] Extends Conditions search to page-content text and expander content in addition to the default page description. When supplied, this parameter must be set to 'true'. This parameter is only valid on the search endpoint.
     * @param {module:api/ConditionsApi~searchConditionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConditionsSearchResponse}
     */
    searchConditions(xMrdScopes, filters, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xMrdScopes' is set
      if (xMrdScopes === undefined || xMrdScopes === null) {
        throw new Error("Missing the required parameter 'xMrdScopes' when calling searchConditions");
      }
      // verify the required parameter 'filters' is set
      if (filters === undefined || filters === null) {
        throw new Error("Missing the required parameter 'filters' when calling searchConditions");
      }

      let pathParams = {
      };
      let queryParams = {
        'filters': this.apiClient.buildCollectionParam(filters, 'multi'),
        'no_html': opts['noHtml'],
        'nhs_links': opts['nhsLinks'],
        'search_all': opts['searchAll']
      };
      let headerParams = {
        'X-Mrd-Scopes': xMrdScopes
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ConditionsSearchResponse;
      return this.apiClient.callApi(
        '/conditions/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
