/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiMrdSdkJavascript);
  }
}(this, function(expect, ApiMrdSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlissAccessibilityFeature', function() {
    it('should create an instance of AlissAccessibilityFeature', function() {
      // uncomment below and update the code to test AlissAccessibilityFeature
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be.a(ApiMrdSdkJavascript.AlissAccessibilityFeature);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be();
    });

    it('should have the property promptquestions (base name: "promptquestions")', function() {
      // uncomment below and update the code to test the property promptquestions
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be();
    });

    it('should have the property icon (base name: "icon")', function() {
      // uncomment below and update the code to test the property icon
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be();
    });

    it('should have the property displayorder (base name: "displayorder")', function() {
      // uncomment below and update the code to test the property displayorder
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be();
    });

    it('should have the property isVirtual (base name: "is_virtual")', function() {
      // uncomment below and update the code to test the property isVirtual
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be();
    });

    it('should have the property isPhysical (base name: "is_physical")', function() {
      // uncomment below and update the code to test the property isPhysical
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be();
    });

    it('should have the property count (base name: "count")', function() {
      // uncomment below and update the code to test the property count
      //var instance = new ApiMrdSdkJavascript.AlissAccessibilityFeature();
      //expect(instance).to.be();
    });

  });

}));
