/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiMrdSdkJavascript);
  }
}(this, function(expect, ApiMrdSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiMrdSdkJavascript.MdsAllField();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MdsAllField', function() {
    it('should create an instance of MdsAllField', function() {
      // uncomment below and update the code to test MdsAllField
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be.a(ApiMrdSdkJavascript.MdsAllField);
    });

    it('should have the property fieldName (base name: "field_name")', function() {
      // uncomment below and update the code to test the property fieldName
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "display_name")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property dataType (base name: "data_type")', function() {
      // uncomment below and update the code to test the property dataType
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property fieldDescription (base name: "field_description")', function() {
      // uncomment below and update the code to test the property fieldDescription
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property fieldExample (base name: "field_example")', function() {
      // uncomment below and update the code to test the property fieldExample
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property fieldOrder (base name: "field_order")', function() {
      // uncomment below and update the code to test the property fieldOrder
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property length (base name: "length")', function() {
      // uncomment below and update the code to test the property length
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property notNull (base name: "not_null")', function() {
      // uncomment below and update the code to test the property notNull
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

    it('should have the property _default (base name: "default")', function() {
      // uncomment below and update the code to test the property _default
      //var instance = new ApiMrdSdkJavascript.MdsAllField();
      //expect(instance).to.be();
    });

  });

}));
