/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiMrdSdkJavascript);
  }
}(this, function(expect, ApiMrdSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiMrdSdkJavascript.MdsFieldTypeResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MdsFieldTypeResponse', function() {
    it('should create an instance of MdsFieldTypeResponse', function() {
      // uncomment below and update the code to test MdsFieldTypeResponse
      //var instance = new ApiMrdSdkJavascript.MdsFieldTypeResponse();
      //expect(instance).to.be.a(ApiMrdSdkJavascript.MdsFieldTypeResponse);
    });

    it('should have the property fieldName (base name: "field_name")', function() {
      // uncomment below and update the code to test the property fieldName
      //var instance = new ApiMrdSdkJavascript.MdsFieldTypeResponse();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "display_name")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new ApiMrdSdkJavascript.MdsFieldTypeResponse();
      //expect(instance).to.be();
    });

    it('should have the property dataType (base name: "data_type")', function() {
      // uncomment below and update the code to test the property dataType
      //var instance = new ApiMrdSdkJavascript.MdsFieldTypeResponse();
      //expect(instance).to.be();
    });

  });

}));
