/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiMrdSdkJavascript);
  }
}(this, function(expect, ApiMrdSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MentalHealthContentElementMainEntityOfPageInner', function() {
    it('should create an instance of MentalHealthContentElementMainEntityOfPageInner', function() {
      // uncomment below and update the code to test MentalHealthContentElementMainEntityOfPageInner
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be.a(ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner);
    });

    it('should have the property type (base name: "@type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property identifier (base name: "identifier")', function() {
      // uncomment below and update the code to test the property identifier
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property headline (base name: "headline")', function() {
      // uncomment below and update the code to test the property headline
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property caption (base name: "caption")', function() {
      // uncomment below and update the code to test the property caption
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property credit (base name: "credit")', function() {
      // uncomment below and update the code to test the property credit
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property acceptedAnswer (base name: "acceptedAnswer")', function() {
      // uncomment below and update the code to test the property acceptedAnswer
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property mainEntity (base name: "mainEntity")', function() {
      // uncomment below and update the code to test the property mainEntity
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property mainEntityOfPage (base name: "mainEntityOfPage")', function() {
      // uncomment below and update the code to test the property mainEntityOfPage
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property hasPart (base name: "hasPart")', function() {
      // uncomment below and update the code to test the property hasPart
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property embedUrl (base name: "embedUrl")', function() {
      // uncomment below and update the code to test the property embedUrl
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property contentUrl (base name: "contentUrl")', function() {
      // uncomment below and update the code to test the property contentUrl
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property alternateName (base name: "alternateName")', function() {
      // uncomment below and update the code to test the property alternateName
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property uploadDate (base name: "uploadDate")', function() {
      // uncomment below and update the code to test the property uploadDate
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property lastReviewed (base name: "lastReviewed")', function() {
      // uncomment below and update the code to test the property lastReviewed
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailUrl (base name: "thumbnailUrl")', function() {
      // uncomment below and update the code to test the property thumbnailUrl
      //var instance = new ApiMrdSdkJavascript.MentalHealthContentElementMainEntityOfPageInner();
      //expect(instance).to.be();
    });

  });

}));
