/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiMrdSdkJavascript);
  }
}(this, function(expect, ApiMrdSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchAlissServicesFiltersParameter', function() {
    it('should create an instance of SearchAlissServicesFiltersParameter', function() {
      // uncomment below and update the code to test SearchAlissServicesFiltersParameter
      //var instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
      //expect(instance).to.be.a(ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter);
    });

    it('should have the property services (base name: "services")', function() {
      // uncomment below and update the code to test the property services
      //var instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
      //expect(instance).to.be();
    });

    it('should have the property organisations (base name: "organisations")', function() {
      // uncomment below and update the code to test the property organisations
      //var instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
      //expect(instance).to.be();
    });

    it('should have the property categories (base name: "categories")', function() {
      // uncomment below and update the code to test the property categories
      //var instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
      //expect(instance).to.be();
    });

    it('should have the property serviceAreas (base name: "service_areas")', function() {
      // uncomment below and update the code to test the property serviceAreas
      //var instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
      //expect(instance).to.be();
    });

    it('should have the property locations (base name: "locations")', function() {
      // uncomment below and update the code to test the property locations
      //var instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
      //expect(instance).to.be();
    });

    it('should have the property accessibilityFeatures (base name: "accessibility_features")', function() {
      // uncomment below and update the code to test the property accessibilityFeatures
      //var instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
      //expect(instance).to.be();
    });

    it('should have the property communityGroups (base name: "community_groups")', function() {
      // uncomment below and update the code to test the property communityGroups
      //var instance = new ApiMrdSdkJavascript.SearchAlissServicesFiltersParameter();
      //expect(instance).to.be();
    });

  });

}));
