/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiMrdSdkJavascript);
  }
}(this, function(expect, ApiMrdSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiMrdSdkJavascript.LivewellApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LivewellApi', function() {
    describe('getLivewellLevelOne', function() {
      it('should call getLivewellLevelOne successfully', function(done) {
        //uncomment below and update the code to test getLivewellLevelOne
        //instance.getLivewellLevelOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLivewellLevelThree', function() {
      it('should call getLivewellLevelThree successfully', function(done) {
        //uncomment below and update the code to test getLivewellLevelThree
        //instance.getLivewellLevelThree(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLivewellLevelTwo', function() {
      it('should call getLivewellLevelTwo successfully', function(done) {
        //uncomment below and update the code to test getLivewellLevelTwo
        //instance.getLivewellLevelTwo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLivewellRoutes', function() {
      it('should call getLivewellRoutes successfully', function(done) {
        //uncomment below and update the code to test getLivewellRoutes
        //instance.getLivewellRoutes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchLivewell', function() {
      it('should call searchLivewell successfully', function(done) {
        //uncomment below and update the code to test searchLivewell
        //instance.searchLivewell(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
