/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiMrdSdkJavascript);
  }
}(this, function(expect, ApiMrdSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiMrdSdkJavascript.MentalHealthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MentalHealthApi', function() {
    describe('getMentalHealthLevelFour', function() {
      it('should call getMentalHealthLevelFour successfully', function(done) {
        //uncomment below and update the code to test getMentalHealthLevelFour
        //instance.getMentalHealthLevelFour(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMentalHealthLevelOne', function() {
      it('should call getMentalHealthLevelOne successfully', function(done) {
        //uncomment below and update the code to test getMentalHealthLevelOne
        //instance.getMentalHealthLevelOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMentalHealthLevelThree', function() {
      it('should call getMentalHealthLevelThree successfully', function(done) {
        //uncomment below and update the code to test getMentalHealthLevelThree
        //instance.getMentalHealthLevelThree(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMentalHealthLevelTwo', function() {
      it('should call getMentalHealthLevelTwo successfully', function(done) {
        //uncomment below and update the code to test getMentalHealthLevelTwo
        //instance.getMentalHealthLevelTwo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMentalHealthRoutes', function() {
      it('should call getMentalHealthRoutes successfully', function(done) {
        //uncomment below and update the code to test getMentalHealthRoutes
        //instance.getMentalHealthRoutes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchMentalHealth', function() {
      it('should call searchMentalHealth successfully', function(done) {
        //uncomment below and update the code to test searchMentalHealth
        //instance.searchMentalHealth(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
